// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: perip2s.proto
// Protobuf C++ Version: 7.35.1

#include "perip2s.pb.h"

#include <algorithm>
#include <type_traits>
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/generated_message_tctable_impl.h"
#include "google/protobuf/internal_visibility.h"
#include "google/protobuf/extension_set.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/wire_format_lite.h"
#include "google/protobuf/descriptor.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/reflection_ops.h"
#include "google/protobuf/wire_format.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"
PROTOBUF_PRAGMA_INIT_SEG
namespace _pb = ::google::protobuf;
namespace _pbi = ::google::protobuf::internal;
namespace _fl = ::google::protobuf::internal::field_layout;
#ifdef PROTOBUF_MESSAGE_GLOBALS
namespace {
PROTOBUF_CONSTINIT ::google::protobuf::internal::ReflectionData
    file_reflection_data[] = {
        // ::peripheral::proto::Heartbeat
        {&::_pbi::kDescriptorMethods, &::descriptor_table_perip2s_2eproto, /* tracker*/ nullptr,},
        // ::peripheral::proto::P2SBoatPositioningSysRegister
        {&::_pbi::kDescriptorMethods, &::descriptor_table_perip2s_2eproto, /* tracker*/ nullptr,},
        // ::peripheral::proto::S2PBoatPositioningSysRegister
        {&::_pbi::kDescriptorMethods, &::descriptor_table_perip2s_2eproto, /* tracker*/ nullptr,},
        // ::peripheral::proto::Position
        {&::_pbi::kDescriptorMethods, &::descriptor_table_perip2s_2eproto, /* tracker*/ nullptr,},
        // ::peripheral::proto::P2SBoatPositioningSysUpdatePos
        {&::_pbi::kDescriptorMethods, &::descriptor_table_perip2s_2eproto, /* tracker*/ nullptr,},
        // ::peripheral::proto::P2SBoatPositioningSysUpdatePoint
        {&::_pbi::kDescriptorMethods, &::descriptor_table_perip2s_2eproto, /* tracker*/ nullptr,},
};
}  // namespace
#endif
namespace peripheral {
namespace proto {
class S2PBoatPositioningSysRegister::_Internal {
 public:
  using HasBits = decltype(::std::declval<S2PBoatPositioningSysRegister>()._impl_._has_bits_);
  static constexpr ::int32_t kHasBitsOffset =
      8 * PROTOBUF_FIELD_OFFSET(S2PBoatPositioningSysRegister, _impl_._has_bits_);
};

constexpr S2PBoatPositioningSysRegister::ParseTableT_ S2PBoatPositioningSysRegister::InternalGenerateParseTable_(const ::_pbi::ClassData* class_data) {
  return ParseTableT_{
    {
      PROTOBUF_FIELD_OFFSET(S2PBoatPositioningSysRegister, _impl_._has_bits_),
      0, // no _extensions_
      1, 0,  // max_field_number, fast_idx_mask
      offsetof(ParseTableT_, field_lookup_table),
      4294967294,  // skipmap
      offsetof(ParseTableT_, field_entries),
      1,  // num_field_entries
      0,  // num_aux_entries
      offsetof(ParseTableT_, field_names),  // no aux_entries
      class_data,
      nullptr,  // post_loop_handler
      ::_pbi::TcParser::GenericFallback,  // fallback
      #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
      ::_pbi::TcParser::GetTable<::peripheral::proto::S2PBoatPositioningSysRegister>(),  // to_prefetch
      #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
    }, {{
      // int32 ret = 1;
      {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(S2PBoatPositioningSysRegister, _impl_.ret_), 0>(),
       {8, 0, 0,
        PROTOBUF_FIELD_OFFSET(S2PBoatPositioningSysRegister, _impl_.ret_)}},
    }}, {{
      65535, 65535
    }}, {{
      // int32 ret = 1;
      {PROTOBUF_FIELD_OFFSET(S2PBoatPositioningSysRegister, _impl_.ret_), _Internal::kHasBitsOffset + 0, 0, (0 | ::_fl::kFcOptional | ::_fl::kInt32)},
    }},
    // no aux_entries
    {{
    }},
  };
}


inline constexpr S2PBoatPositioningSysRegister::Impl_::Impl_(
    [[maybe_unused]] ::google::protobuf::internal::InternalVisibility visibility,
    ::_pbi::ConstantInitialized) noexcept
      : _cached_size_{0},
        ret_{0} {}

template <typename>
constexpr S2PBoatPositioningSysRegister::S2PBoatPositioningSysRegister(::_pbi::ConstantInitialized,
                       const ::_pbi::ClassData* PROTOBUF_NONNULL class_data)
    : ::google::protobuf::Message(
#if defined(PROTOBUF_CUSTOM_VTABLE)
          class_data
#endif  // PROTOBUF_CUSTOM_VTABLE
          ),
      _impl_(internal_visibility(), ::_pbi::ConstantInitialized()) {
}
inline void* PROTOBUF_NONNULL S2PBoatPositioningSysRegister::PlacementNew_(
    const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena) {
  return ::new (mem) S2PBoatPositioningSysRegister(arena);
}
constexpr auto S2PBoatPositioningSysRegister::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::ZeroInit(sizeof(S2PBoatPositioningSysRegister), alignof(S2PBoatPositioningSysRegister));
}
constexpr auto S2PBoatPositioningSysRegister::InternalGenerateClassData_(
    const MessageLite& prototype,
    const ::google::protobuf::internal::TcParseTableBase* tc_table) {
  return ::google::protobuf::internal::ClassDataFull{
      ::google::protobuf::internal::ClassData{
          &prototype,
#ifndef PROTOBUF_MESSAGE_GLOBALS
          &_table_.header,
#else
          tc_table,
#endif
          nullptr,  // IsInitialized
          &S2PBoatPositioningSysRegister::MergeImpl,
          ::google::protobuf::Message::GetNewImpl<S2PBoatPositioningSysRegister>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
          &S2PBoatPositioningSysRegister::SharedDtor,
          ::google::protobuf::Message::GetClearImpl<S2PBoatPositioningSysRegister>(), &S2PBoatPositioningSysRegister::ByteSizeLong,
              &S2PBoatPositioningSysRegister::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
          PROTOBUF_FIELD_OFFSET(S2PBoatPositioningSysRegister, _impl_._cached_size_),
          false,
      },
#ifdef PROTOBUF_MESSAGE_GLOBALS
      &file_reflection_data[2],
#else   // !PROTOBUF_MESSAGE_GLOBALS
      &::_pbi::kDescriptorMethods,
      &descriptor_table_perip2s_2eproto,
      nullptr,  // tracker
#endif  // PROTOBUF_MESSAGE_GLOBALS
  };
}
struct S2PBoatPositioningSysRegisterGlobalsTypeInternal : ::_pbi::MessageGlobalsBase {
  constexpr S2PBoatPositioningSysRegisterGlobalsTypeInternal()
      :
#ifndef PROTOBUF_MESSAGE_GLOBALS
        _default(::_pbi::ConstantInitialized{},
                 S2PBoatPositioningSysRegister_class_data_.base())
#else   // !PROTOBUF_MESSAGE_GLOBALS
        MessageGlobalsBase(S2PBoatPositioningSysRegister::InternalGenerateClassData_(
            _default, &S2PBoatPositioningSysRegister_globals_._table.header)),
        _default(::_pbi::ConstantInitialized{}, GetClassData()),
        _table(::_pbi::PrivateAccess::GenerateParseTable<S2PBoatPositioningSysRegister>(
            GetClassData()))
#endif  // PROTOBUF_MESSAGE_GLOBALS
  {
  }
  ~S2PBoatPositioningSysRegisterGlobalsTypeInternal() {}
  union {
    alignas(::_pbi::kMaxMessageAlignment) S2PBoatPositioningSysRegister _default;
  };
#ifdef PROTOBUF_MESSAGE_GLOBALS
  decltype(::_pbi::PrivateAccess::GenerateParseTable<S2PBoatPositioningSysRegister>(
      ::std::declval<const ::_pbi::ClassData*>())) _table;
#endif
};
#ifdef PROTOBUF_MESSAGE_GLOBALS
static_assert(PROTOBUF_FIELD_OFFSET(S2PBoatPositioningSysRegisterGlobalsTypeInternal, _default) ==
              ::_pbi::MessageGlobalsBase::OffsetToDefault());
#endif  // PROTOBUF_MESSAGE_GLOBALS

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 PROTOBUF_MESSAGE_GLOBALS_CONST S2PBoatPositioningSysRegisterGlobalsTypeInternal S2PBoatPositioningSysRegister_globals_
        PROTOBUF_MESSAGE_GLOBALS_SECTION(.data.rel.ro);
#if defined(PROTOBUF_CUSTOM_VTABLE)
namespace {
const ::_pbi::ClassData* S2PBoatPositioningSysRegister_get_class_data() {
#ifdef PROTOBUF_MESSAGE_GLOBALS
  return S2PBoatPositioningSysRegister_globals_.GetClassData();
#else
  return S2PBoatPositioningSysRegister_class_data_.base();
#endif  // PROTOBUF_MESSAGE_GLOBALS
}
}  // namespace
#endif  // PROTOBUF_CUSTOM_VTABLE
class Position::_Internal {
 public:
  using HasBits = decltype(::std::declval<Position>()._impl_._has_bits_);
  static constexpr ::int32_t kHasBitsOffset =
      8 * PROTOBUF_FIELD_OFFSET(Position, _impl_._has_bits_);
};

constexpr Position::ParseTableT_ Position::InternalGenerateParseTable_(const ::_pbi::ClassData* class_data) {
  return ParseTableT_{
    {
      PROTOBUF_FIELD_OFFSET(Position, _impl_._has_bits_),
      0, // no _extensions_
      3, 24,  // max_field_number, fast_idx_mask
      offsetof(ParseTableT_, field_lookup_table),
      4294967288,  // skipmap
      offsetof(ParseTableT_, field_entries),
      3,  // num_field_entries
      0,  // num_aux_entries
      offsetof(ParseTableT_, field_names),  // no aux_entries
      class_data,
      nullptr,  // post_loop_handler
      ::_pbi::TcParser::GenericFallback,  // fallback
      #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
      ::_pbi::TcParser::GetTable<::peripheral::proto::Position>(),  // to_prefetch
      #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
    }, {{
      {::_pbi::TcParser::MiniParse, {}},
      // float x = 1;
      {::_pbi::TcParser::FastF32S1,
       {13, 0, 0,
        PROTOBUF_FIELD_OFFSET(Position, _impl_.x_)}},
      // float y = 2;
      {::_pbi::TcParser::FastF32S1,
       {21, 1, 0,
        PROTOBUF_FIELD_OFFSET(Position, _impl_.y_)}},
      // float z = 3;
      {::_pbi::TcParser::FastF32S1,
       {29, 2, 0,
        PROTOBUF_FIELD_OFFSET(Position, _impl_.z_)}},
    }}, {{
      65535, 65535
    }}, {{
      // float x = 1;
      {PROTOBUF_FIELD_OFFSET(Position, _impl_.x_), _Internal::kHasBitsOffset + 0, 0, (0 | ::_fl::kFcOptional | ::_fl::kFloat)},
      // float y = 2;
      {PROTOBUF_FIELD_OFFSET(Position, _impl_.y_), _Internal::kHasBitsOffset + 1, 0, (0 | ::_fl::kFcOptional | ::_fl::kFloat)},
      // float z = 3;
      {PROTOBUF_FIELD_OFFSET(Position, _impl_.z_), _Internal::kHasBitsOffset + 2, 0, (0 | ::_fl::kFcOptional | ::_fl::kFloat)},
    }},
    // no aux_entries
    {{
    }},
  };
}


inline constexpr Position::Impl_::Impl_(
    [[maybe_unused]] ::google::protobuf::internal::InternalVisibility visibility,
    ::_pbi::ConstantInitialized) noexcept
      : _cached_size_{0},
        x_{0},
        y_{0},
        z_{0} {}

template <typename>
constexpr Position::Position(::_pbi::ConstantInitialized,
                       const ::_pbi::ClassData* PROTOBUF_NONNULL class_data)
    : ::google::protobuf::Message(
#if defined(PROTOBUF_CUSTOM_VTABLE)
          class_data
#endif  // PROTOBUF_CUSTOM_VTABLE
          ),
      _impl_(internal_visibility(), ::_pbi::ConstantInitialized()) {
}
inline void* PROTOBUF_NONNULL Position::PlacementNew_(
    const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena) {
  return ::new (mem) Position(arena);
}
constexpr auto Position::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::ZeroInit(sizeof(Position), alignof(Position));
}
constexpr auto Position::InternalGenerateClassData_(
    const MessageLite& prototype,
    const ::google::protobuf::internal::TcParseTableBase* tc_table) {
  return ::google::protobuf::internal::ClassDataFull{
      ::google::protobuf::internal::ClassData{
          &prototype,
#ifndef PROTOBUF_MESSAGE_GLOBALS
          &_table_.header,
#else
          tc_table,
#endif
          nullptr,  // IsInitialized
          &Position::MergeImpl,
          ::google::protobuf::Message::GetNewImpl<Position>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
          &Position::SharedDtor,
          ::google::protobuf::Message::GetClearImpl<Position>(), &Position::ByteSizeLong,
              &Position::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
          PROTOBUF_FIELD_OFFSET(Position, _impl_._cached_size_),
          false,
      },
#ifdef PROTOBUF_MESSAGE_GLOBALS
      &file_reflection_data[3],
#else   // !PROTOBUF_MESSAGE_GLOBALS
      &::_pbi::kDescriptorMethods,
      &descriptor_table_perip2s_2eproto,
      nullptr,  // tracker
#endif  // PROTOBUF_MESSAGE_GLOBALS
  };
}
struct PositionGlobalsTypeInternal : ::_pbi::MessageGlobalsBase {
  constexpr PositionGlobalsTypeInternal()
      :
#ifndef PROTOBUF_MESSAGE_GLOBALS
        _default(::_pbi::ConstantInitialized{},
                 Position_class_data_.base())
#else   // !PROTOBUF_MESSAGE_GLOBALS
        MessageGlobalsBase(Position::InternalGenerateClassData_(
            _default, &Position_globals_._table.header)),
        _default(::_pbi::ConstantInitialized{}, GetClassData()),
        _table(::_pbi::PrivateAccess::GenerateParseTable<Position>(
            GetClassData()))
#endif  // PROTOBUF_MESSAGE_GLOBALS
  {
  }
  ~PositionGlobalsTypeInternal() {}
  union {
    alignas(::_pbi::kMaxMessageAlignment) Position _default;
  };
#ifdef PROTOBUF_MESSAGE_GLOBALS
  decltype(::_pbi::PrivateAccess::GenerateParseTable<Position>(
      ::std::declval<const ::_pbi::ClassData*>())) _table;
#endif
};
#ifdef PROTOBUF_MESSAGE_GLOBALS
static_assert(PROTOBUF_FIELD_OFFSET(PositionGlobalsTypeInternal, _default) ==
              ::_pbi::MessageGlobalsBase::OffsetToDefault());
#endif  // PROTOBUF_MESSAGE_GLOBALS

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 PROTOBUF_MESSAGE_GLOBALS_CONST PositionGlobalsTypeInternal Position_globals_
        PROTOBUF_MESSAGE_GLOBALS_SECTION(.data.rel.ro);
#if defined(PROTOBUF_CUSTOM_VTABLE)
namespace {
const ::_pbi::ClassData* Position_get_class_data() {
#ifdef PROTOBUF_MESSAGE_GLOBALS
  return Position_globals_.GetClassData();
#else
  return Position_class_data_.base();
#endif  // PROTOBUF_MESSAGE_GLOBALS
}
}  // namespace
#endif  // PROTOBUF_CUSTOM_VTABLE
class P2SBoatPositioningSysUpdatePoint::_Internal {
 public:
  using HasBits = decltype(::std::declval<P2SBoatPositioningSysUpdatePoint>()._impl_._has_bits_);
  static constexpr ::int32_t kHasBitsOffset =
      8 * PROTOBUF_FIELD_OFFSET(P2SBoatPositioningSysUpdatePoint, _impl_._has_bits_);
};

constexpr P2SBoatPositioningSysUpdatePoint::ParseTableT_ P2SBoatPositioningSysUpdatePoint::InternalGenerateParseTable_(const ::_pbi::ClassData* class_data) {
  return ParseTableT_{
    {
      PROTOBUF_FIELD_OFFSET(P2SBoatPositioningSysUpdatePoint, _impl_._has_bits_),
      0, // no _extensions_
      3, 24,  // max_field_number, fast_idx_mask
      offsetof(ParseTableT_, field_lookup_table),
      4294967288,  // skipmap
      offsetof(ParseTableT_, field_entries),
      3,  // num_field_entries
      0,  // num_aux_entries
      offsetof(ParseTableT_, field_names),  // no aux_entries
      class_data,
      nullptr,  // post_loop_handler
      ::_pbi::TcParser::GenericFallback,  // fallback
      #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
      ::_pbi::TcParser::GetTable<::peripheral::proto::P2SBoatPositioningSysUpdatePoint>(),  // to_prefetch
      #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
    }, {{
      {::_pbi::TcParser::MiniParse, {}},
      // int32 boat_id = 1;
      {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(P2SBoatPositioningSysUpdatePoint, _impl_.boat_id_), 0>(),
       {8, 0, 0,
        PROTOBUF_FIELD_OFFSET(P2SBoatPositioningSysUpdatePoint, _impl_.boat_id_)}},
      // int32 point_id = 2;
      {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(P2SBoatPositioningSysUpdatePoint, _impl_.point_id_), 1>(),
       {16, 1, 0,
        PROTOBUF_FIELD_OFFSET(P2SBoatPositioningSysUpdatePoint, _impl_.point_id_)}},
      // int64 timestamp = 3;
      {::_pbi::TcParser::SingularVarintNoZag1<::uint64_t, offsetof(P2SBoatPositioningSysUpdatePoint, _impl_.timestamp_), 2>(),
       {24, 2, 0,
        PROTOBUF_FIELD_OFFSET(P2SBoatPositioningSysUpdatePoint, _impl_.timestamp_)}},
    }}, {{
      65535, 65535
    }}, {{
      // int32 boat_id = 1;
      {PROTOBUF_FIELD_OFFSET(P2SBoatPositioningSysUpdatePoint, _impl_.boat_id_), _Internal::kHasBitsOffset + 0, 0, (0 | ::_fl::kFcOptional | ::_fl::kInt32)},
      // int32 point_id = 2;
      {PROTOBUF_FIELD_OFFSET(P2SBoatPositioningSysUpdatePoint, _impl_.point_id_), _Internal::kHasBitsOffset + 1, 0, (0 | ::_fl::kFcOptional | ::_fl::kInt32)},
      // int64 timestamp = 3;
      {PROTOBUF_FIELD_OFFSET(P2SBoatPositioningSysUpdatePoint, _impl_.timestamp_), _Internal::kHasBitsOffset + 2, 0, (0 | ::_fl::kFcOptional | ::_fl::kInt64)},
    }},
    // no aux_entries
    {{
    }},
  };
}


inline constexpr P2SBoatPositioningSysUpdatePoint::Impl_::Impl_(
    [[maybe_unused]] ::google::protobuf::internal::InternalVisibility visibility,
    ::_pbi::ConstantInitialized) noexcept
      : _cached_size_{0},
        boat_id_{0},
        point_id_{0},
        timestamp_{::int64_t{0}} {}

template <typename>
constexpr P2SBoatPositioningSysUpdatePoint::P2SBoatPositioningSysUpdatePoint(::_pbi::ConstantInitialized,
                       const ::_pbi::ClassData* PROTOBUF_NONNULL class_data)
    : ::google::protobuf::Message(
#if defined(PROTOBUF_CUSTOM_VTABLE)
          class_data
#endif  // PROTOBUF_CUSTOM_VTABLE
          ),
      _impl_(internal_visibility(), ::_pbi::ConstantInitialized()) {
}
inline void* PROTOBUF_NONNULL P2SBoatPositioningSysUpdatePoint::PlacementNew_(
    const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena) {
  return ::new (mem) P2SBoatPositioningSysUpdatePoint(arena);
}
constexpr auto P2SBoatPositioningSysUpdatePoint::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::ZeroInit(sizeof(P2SBoatPositioningSysUpdatePoint), alignof(P2SBoatPositioningSysUpdatePoint));
}
constexpr auto P2SBoatPositioningSysUpdatePoint::InternalGenerateClassData_(
    const MessageLite& prototype,
    const ::google::protobuf::internal::TcParseTableBase* tc_table) {
  return ::google::protobuf::internal::ClassDataFull{
      ::google::protobuf::internal::ClassData{
          &prototype,
#ifndef PROTOBUF_MESSAGE_GLOBALS
          &_table_.header,
#else
          tc_table,
#endif
          nullptr,  // IsInitialized
          &P2SBoatPositioningSysUpdatePoint::MergeImpl,
          ::google::protobuf::Message::GetNewImpl<P2SBoatPositioningSysUpdatePoint>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
          &P2SBoatPositioningSysUpdatePoint::SharedDtor,
          ::google::protobuf::Message::GetClearImpl<P2SBoatPositioningSysUpdatePoint>(), &P2SBoatPositioningSysUpdatePoint::ByteSizeLong,
              &P2SBoatPositioningSysUpdatePoint::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
          PROTOBUF_FIELD_OFFSET(P2SBoatPositioningSysUpdatePoint, _impl_._cached_size_),
          false,
      },
#ifdef PROTOBUF_MESSAGE_GLOBALS
      &file_reflection_data[5],
#else   // !PROTOBUF_MESSAGE_GLOBALS
      &::_pbi::kDescriptorMethods,
      &descriptor_table_perip2s_2eproto,
      nullptr,  // tracker
#endif  // PROTOBUF_MESSAGE_GLOBALS
  };
}
struct P2SBoatPositioningSysUpdatePointGlobalsTypeInternal : ::_pbi::MessageGlobalsBase {
  constexpr P2SBoatPositioningSysUpdatePointGlobalsTypeInternal()
      :
#ifndef PROTOBUF_MESSAGE_GLOBALS
        _default(::_pbi::ConstantInitialized{},
                 P2SBoatPositioningSysUpdatePoint_class_data_.base())
#else   // !PROTOBUF_MESSAGE_GLOBALS
        MessageGlobalsBase(P2SBoatPositioningSysUpdatePoint::InternalGenerateClassData_(
            _default, &P2SBoatPositioningSysUpdatePoint_globals_._table.header)),
        _default(::_pbi::ConstantInitialized{}, GetClassData()),
        _table(::_pbi::PrivateAccess::GenerateParseTable<P2SBoatPositioningSysUpdatePoint>(
            GetClassData()))
#endif  // PROTOBUF_MESSAGE_GLOBALS
  {
  }
  ~P2SBoatPositioningSysUpdatePointGlobalsTypeInternal() {}
  union {
    alignas(::_pbi::kMaxMessageAlignment) P2SBoatPositioningSysUpdatePoint _default;
  };
#ifdef PROTOBUF_MESSAGE_GLOBALS
  decltype(::_pbi::PrivateAccess::GenerateParseTable<P2SBoatPositioningSysUpdatePoint>(
      ::std::declval<const ::_pbi::ClassData*>())) _table;
#endif
};
#ifdef PROTOBUF_MESSAGE_GLOBALS
static_assert(PROTOBUF_FIELD_OFFSET(P2SBoatPositioningSysUpdatePointGlobalsTypeInternal, _default) ==
              ::_pbi::MessageGlobalsBase::OffsetToDefault());
#endif  // PROTOBUF_MESSAGE_GLOBALS

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 PROTOBUF_MESSAGE_GLOBALS_CONST P2SBoatPositioningSysUpdatePointGlobalsTypeInternal P2SBoatPositioningSysUpdatePoint_globals_
        PROTOBUF_MESSAGE_GLOBALS_SECTION(.data.rel.ro);
#if defined(PROTOBUF_CUSTOM_VTABLE)
namespace {
const ::_pbi::ClassData* P2SBoatPositioningSysUpdatePoint_get_class_data() {
#ifdef PROTOBUF_MESSAGE_GLOBALS
  return P2SBoatPositioningSysUpdatePoint_globals_.GetClassData();
#else
  return P2SBoatPositioningSysUpdatePoint_class_data_.base();
#endif  // PROTOBUF_MESSAGE_GLOBALS
}
}  // namespace
#endif  // PROTOBUF_CUSTOM_VTABLE
class P2SBoatPositioningSysRegister::_Internal {
 public:
};

constexpr P2SBoatPositioningSysRegister::ParseTableT_ P2SBoatPositioningSysRegister::InternalGenerateParseTable_(const ::_pbi::ClassData* class_data) {
  return ParseTableT_{
    {
      PROTOBUF_FIELD_OFFSET(P2SBoatPositioningSysRegister,
                            _impl_._cached_size_),  // no hasbits
      0, // no _extensions_
      0, 0,  // max_field_number, fast_idx_mask
      offsetof(ParseTableT_, field_lookup_table),
      4294967295,  // skipmap
      offsetof(ParseTableT_, field_names),  // no field_entries
      0,  // num_field_entries
      0,  // num_aux_entries
      offsetof(ParseTableT_, field_names),  // no aux_entries
      class_data,
      nullptr,  // post_loop_handler
      ::_pbi::TcParser::GenericFallback,  // fallback
      #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
      ::_pbi::TcParser::GetTable<::peripheral::proto::P2SBoatPositioningSysRegister>(),  // to_prefetch
      #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
    }, {{
      {::_pbi::TcParser::MiniParse, {}},
    }}, {{
      65535, 65535
    }}, // no field_entries, or aux_entries
    {{
    }},
  };
}

template <typename>
constexpr P2SBoatPositioningSysRegister::P2SBoatPositioningSysRegister(::_pbi::ConstantInitialized,
                       const ::_pbi::ClassData* PROTOBUF_NONNULL class_data)
    : ::google::protobuf::internal::ZeroFieldsBase(
#if defined(PROTOBUF_CUSTOM_VTABLE)
          class_data
#endif  // PROTOBUF_CUSTOM_VTABLE
      ) {
}
inline void* PROTOBUF_NONNULL P2SBoatPositioningSysRegister::PlacementNew_(
    const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena) {
  return ::new (mem) P2SBoatPositioningSysRegister(arena);
}
constexpr auto P2SBoatPositioningSysRegister::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::ZeroInit(sizeof(P2SBoatPositioningSysRegister), alignof(P2SBoatPositioningSysRegister));
}
constexpr auto P2SBoatPositioningSysRegister::InternalGenerateClassData_(
    const MessageLite& prototype,
    const ::google::protobuf::internal::TcParseTableBase* tc_table) {
  return ::google::protobuf::internal::ClassDataFull{
      ::google::protobuf::internal::ClassData{
          &prototype,
#ifndef PROTOBUF_MESSAGE_GLOBALS
          &_table_.header,
#else
          tc_table,
#endif
          nullptr,  // IsInitialized
          &P2SBoatPositioningSysRegister::MergeImpl,
          ::google::protobuf::internal::ZeroFieldsBase::GetNewImpl<P2SBoatPositioningSysRegister>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
          &P2SBoatPositioningSysRegister::SharedDtor,
          ::google::protobuf::internal::ZeroFieldsBase::GetClearImpl<P2SBoatPositioningSysRegister>(), &P2SBoatPositioningSysRegister::ByteSizeLong,
              &P2SBoatPositioningSysRegister::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
          PROTOBUF_FIELD_OFFSET(P2SBoatPositioningSysRegister, _impl_._cached_size_),
          false,
      },
#ifdef PROTOBUF_MESSAGE_GLOBALS
      &file_reflection_data[1],
#else   // !PROTOBUF_MESSAGE_GLOBALS
      &::_pbi::kDescriptorMethods,
      &descriptor_table_perip2s_2eproto,
      nullptr,  // tracker
#endif  // PROTOBUF_MESSAGE_GLOBALS
  };
}
struct P2SBoatPositioningSysRegisterGlobalsTypeInternal : ::_pbi::MessageGlobalsBase {
  constexpr P2SBoatPositioningSysRegisterGlobalsTypeInternal()
      :
#ifndef PROTOBUF_MESSAGE_GLOBALS
        _default(::_pbi::ConstantInitialized{},
                 P2SBoatPositioningSysRegister_class_data_.base())
#else   // !PROTOBUF_MESSAGE_GLOBALS
        MessageGlobalsBase(P2SBoatPositioningSysRegister::InternalGenerateClassData_(
            _default, &P2SBoatPositioningSysRegister_globals_._table.header)),
        _default(::_pbi::ConstantInitialized{}, GetClassData()),
        _table(::_pbi::PrivateAccess::GenerateParseTable<P2SBoatPositioningSysRegister>(
            GetClassData()))
#endif  // PROTOBUF_MESSAGE_GLOBALS
  {
  }
  ~P2SBoatPositioningSysRegisterGlobalsTypeInternal() {}
  union {
    alignas(::_pbi::kMaxMessageAlignment) P2SBoatPositioningSysRegister _default;
  };
#ifdef PROTOBUF_MESSAGE_GLOBALS
  decltype(::_pbi::PrivateAccess::GenerateParseTable<P2SBoatPositioningSysRegister>(
      ::std::declval<const ::_pbi::ClassData*>())) _table;
#endif
};
#ifdef PROTOBUF_MESSAGE_GLOBALS
static_assert(PROTOBUF_FIELD_OFFSET(P2SBoatPositioningSysRegisterGlobalsTypeInternal, _default) ==
              ::_pbi::MessageGlobalsBase::OffsetToDefault());
#endif  // PROTOBUF_MESSAGE_GLOBALS

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 PROTOBUF_MESSAGE_GLOBALS_CONST P2SBoatPositioningSysRegisterGlobalsTypeInternal P2SBoatPositioningSysRegister_globals_
        PROTOBUF_MESSAGE_GLOBALS_SECTION(.data.rel.ro);
#if defined(PROTOBUF_CUSTOM_VTABLE)
namespace {
const ::_pbi::ClassData* P2SBoatPositioningSysRegister_get_class_data() {
#ifdef PROTOBUF_MESSAGE_GLOBALS
  return P2SBoatPositioningSysRegister_globals_.GetClassData();
#else
  return P2SBoatPositioningSysRegister_class_data_.base();
#endif  // PROTOBUF_MESSAGE_GLOBALS
}
}  // namespace
#endif  // PROTOBUF_CUSTOM_VTABLE
class Heartbeat::_Internal {
 public:
};

constexpr Heartbeat::ParseTableT_ Heartbeat::InternalGenerateParseTable_(const ::_pbi::ClassData* class_data) {
  return ParseTableT_{
    {
      PROTOBUF_FIELD_OFFSET(Heartbeat,
                            _impl_._cached_size_),  // no hasbits
      0, // no _extensions_
      0, 0,  // max_field_number, fast_idx_mask
      offsetof(ParseTableT_, field_lookup_table),
      4294967295,  // skipmap
      offsetof(ParseTableT_, field_names),  // no field_entries
      0,  // num_field_entries
      0,  // num_aux_entries
      offsetof(ParseTableT_, field_names),  // no aux_entries
      class_data,
      nullptr,  // post_loop_handler
      ::_pbi::TcParser::GenericFallback,  // fallback
      #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
      ::_pbi::TcParser::GetTable<::peripheral::proto::Heartbeat>(),  // to_prefetch
      #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
    }, {{
      {::_pbi::TcParser::MiniParse, {}},
    }}, {{
      65535, 65535
    }}, // no field_entries, or aux_entries
    {{
    }},
  };
}

template <typename>
constexpr Heartbeat::Heartbeat(::_pbi::ConstantInitialized,
                       const ::_pbi::ClassData* PROTOBUF_NONNULL class_data)
    : ::google::protobuf::internal::ZeroFieldsBase(
#if defined(PROTOBUF_CUSTOM_VTABLE)
          class_data
#endif  // PROTOBUF_CUSTOM_VTABLE
      ) {
}
inline void* PROTOBUF_NONNULL Heartbeat::PlacementNew_(
    const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena) {
  return ::new (mem) Heartbeat(arena);
}
constexpr auto Heartbeat::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::ZeroInit(sizeof(Heartbeat), alignof(Heartbeat));
}
constexpr auto Heartbeat::InternalGenerateClassData_(
    const MessageLite& prototype,
    const ::google::protobuf::internal::TcParseTableBase* tc_table) {
  return ::google::protobuf::internal::ClassDataFull{
      ::google::protobuf::internal::ClassData{
          &prototype,
#ifndef PROTOBUF_MESSAGE_GLOBALS
          &_table_.header,
#else
          tc_table,
#endif
          nullptr,  // IsInitialized
          &Heartbeat::MergeImpl,
          ::google::protobuf::internal::ZeroFieldsBase::GetNewImpl<Heartbeat>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
          &Heartbeat::SharedDtor,
          ::google::protobuf::internal::ZeroFieldsBase::GetClearImpl<Heartbeat>(), &Heartbeat::ByteSizeLong,
              &Heartbeat::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
          PROTOBUF_FIELD_OFFSET(Heartbeat, _impl_._cached_size_),
          false,
      },
#ifdef PROTOBUF_MESSAGE_GLOBALS
      &file_reflection_data[0],
#else   // !PROTOBUF_MESSAGE_GLOBALS
      &::_pbi::kDescriptorMethods,
      &descriptor_table_perip2s_2eproto,
      nullptr,  // tracker
#endif  // PROTOBUF_MESSAGE_GLOBALS
  };
}
struct HeartbeatGlobalsTypeInternal : ::_pbi::MessageGlobalsBase {
  constexpr HeartbeatGlobalsTypeInternal()
      :
#ifndef PROTOBUF_MESSAGE_GLOBALS
        _default(::_pbi::ConstantInitialized{},
                 Heartbeat_class_data_.base())
#else   // !PROTOBUF_MESSAGE_GLOBALS
        MessageGlobalsBase(Heartbeat::InternalGenerateClassData_(
            _default, &Heartbeat_globals_._table.header)),
        _default(::_pbi::ConstantInitialized{}, GetClassData()),
        _table(::_pbi::PrivateAccess::GenerateParseTable<Heartbeat>(
            GetClassData()))
#endif  // PROTOBUF_MESSAGE_GLOBALS
  {
  }
  ~HeartbeatGlobalsTypeInternal() {}
  union {
    alignas(::_pbi::kMaxMessageAlignment) Heartbeat _default;
  };
#ifdef PROTOBUF_MESSAGE_GLOBALS
  decltype(::_pbi::PrivateAccess::GenerateParseTable<Heartbeat>(
      ::std::declval<const ::_pbi::ClassData*>())) _table;
#endif
};
#ifdef PROTOBUF_MESSAGE_GLOBALS
static_assert(PROTOBUF_FIELD_OFFSET(HeartbeatGlobalsTypeInternal, _default) ==
              ::_pbi::MessageGlobalsBase::OffsetToDefault());
#endif  // PROTOBUF_MESSAGE_GLOBALS

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 PROTOBUF_MESSAGE_GLOBALS_CONST HeartbeatGlobalsTypeInternal Heartbeat_globals_
        PROTOBUF_MESSAGE_GLOBALS_SECTION(.data.rel.ro);
#if defined(PROTOBUF_CUSTOM_VTABLE)
namespace {
const ::_pbi::ClassData* Heartbeat_get_class_data() {
#ifdef PROTOBUF_MESSAGE_GLOBALS
  return Heartbeat_globals_.GetClassData();
#else
  return Heartbeat_class_data_.base();
#endif  // PROTOBUF_MESSAGE_GLOBALS
}
}  // namespace
#endif  // PROTOBUF_CUSTOM_VTABLE
class P2SBoatPositioningSysUpdatePos::_Internal {
 public:
  using HasBits = decltype(::std::declval<P2SBoatPositioningSysUpdatePos>()._impl_._has_bits_);
  static constexpr ::int32_t kHasBitsOffset =
      8 * PROTOBUF_FIELD_OFFSET(P2SBoatPositioningSysUpdatePos, _impl_._has_bits_);
};

constexpr P2SBoatPositioningSysUpdatePos::ParseTableT_ P2SBoatPositioningSysUpdatePos::InternalGenerateParseTable_(const ::_pbi::ClassData* class_data) {
  return ParseTableT_{
    {
      PROTOBUF_FIELD_OFFSET(P2SBoatPositioningSysUpdatePos, _impl_._has_bits_),
      0, // no _extensions_
      3, 24,  // max_field_number, fast_idx_mask
      offsetof(ParseTableT_, field_lookup_table),
      4294967288,  // skipmap
      offsetof(ParseTableT_, field_entries),
      3,  // num_field_entries
      1,  // num_aux_entries
      offsetof(ParseTableT_, aux_entries),
      class_data,
      nullptr,  // post_loop_handler
      ::_pbi::TcParser::GenericFallback,  // fallback
      #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
      ::_pbi::TcParser::GetTable<::peripheral::proto::P2SBoatPositioningSysUpdatePos>(),  // to_prefetch
      #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
    }, {{
      {::_pbi::TcParser::MiniParse, {}},
      // int32 boat_id = 1;
      {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(P2SBoatPositioningSysUpdatePos, _impl_.boat_id_), 2>(),
       {8, 2, 0,
        PROTOBUF_FIELD_OFFSET(P2SBoatPositioningSysUpdatePos, _impl_.boat_id_)}},
      // .peripheral.proto.Position pos = 2;
      {::_pbi::TcParser::FastMtS1,
       {18, 0, 0,
        PROTOBUF_FIELD_OFFSET(P2SBoatPositioningSysUpdatePos, _impl_.pos_)}},
      // int64 timestamp = 3;
      {::_pbi::TcParser::SingularVarintNoZag1<::uint64_t, offsetof(P2SBoatPositioningSysUpdatePos, _impl_.timestamp_), 1>(),
       {24, 1, 0,
        PROTOBUF_FIELD_OFFSET(P2SBoatPositioningSysUpdatePos, _impl_.timestamp_)}},
    }}, {{
      65535, 65535
    }}, {{
      // int32 boat_id = 1;
      {PROTOBUF_FIELD_OFFSET(P2SBoatPositioningSysUpdatePos, _impl_.boat_id_), _Internal::kHasBitsOffset + 2, 0, (0 | ::_fl::kFcOptional | ::_fl::kInt32)},
      // .peripheral.proto.Position pos = 2;
      {PROTOBUF_FIELD_OFFSET(P2SBoatPositioningSysUpdatePos, _impl_.pos_), _Internal::kHasBitsOffset + 0, 0, (0 | ::_fl::kFcOptional | ::_fl::kMessage | ::_fl::kTvTable)},
      // int64 timestamp = 3;
      {PROTOBUF_FIELD_OFFSET(P2SBoatPositioningSysUpdatePos, _impl_.timestamp_), _Internal::kHasBitsOffset + 1, 0, (0 | ::_fl::kFcOptional | ::_fl::kInt64)},
    }},
    {{
        #ifndef PROTOBUF_MESSAGE_GLOBALS
        {::_pbi::TcParser::GetTable<::peripheral::proto::Position>()},
        #else
        {::_pbi::FieldAuxMessageGlobals(), &::peripheral::proto::Position_globals_},
        #endif
    }},
    {{
    }},
  };
}


inline constexpr P2SBoatPositioningSysUpdatePos::Impl_::Impl_(
    [[maybe_unused]] ::google::protobuf::internal::InternalVisibility visibility,
    ::_pbi::ConstantInitialized) noexcept
      : _cached_size_{0},
        pos_{nullptr},
        timestamp_{::int64_t{0}},
        boat_id_{0} {}

template <typename>
constexpr P2SBoatPositioningSysUpdatePos::P2SBoatPositioningSysUpdatePos(::_pbi::ConstantInitialized,
                       const ::_pbi::ClassData* PROTOBUF_NONNULL class_data)
    : ::google::protobuf::Message(
#if defined(PROTOBUF_CUSTOM_VTABLE)
          class_data
#endif  // PROTOBUF_CUSTOM_VTABLE
          ),
      _impl_(internal_visibility(), ::_pbi::ConstantInitialized()) {
}
inline void* PROTOBUF_NONNULL P2SBoatPositioningSysUpdatePos::PlacementNew_(
    const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena) {
  return ::new (mem) P2SBoatPositioningSysUpdatePos(arena);
}
constexpr auto P2SBoatPositioningSysUpdatePos::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::ZeroInit(sizeof(P2SBoatPositioningSysUpdatePos), alignof(P2SBoatPositioningSysUpdatePos));
}
constexpr auto P2SBoatPositioningSysUpdatePos::InternalGenerateClassData_(
    const MessageLite& prototype,
    const ::google::protobuf::internal::TcParseTableBase* tc_table) {
  return ::google::protobuf::internal::ClassDataFull{
      ::google::protobuf::internal::ClassData{
          &prototype,
#ifndef PROTOBUF_MESSAGE_GLOBALS
          &_table_.header,
#else
          tc_table,
#endif
          nullptr,  // IsInitialized
          &P2SBoatPositioningSysUpdatePos::MergeImpl,
          ::google::protobuf::Message::GetNewImpl<P2SBoatPositioningSysUpdatePos>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
          &P2SBoatPositioningSysUpdatePos::SharedDtor,
          ::google::protobuf::Message::GetClearImpl<P2SBoatPositioningSysUpdatePos>(), &P2SBoatPositioningSysUpdatePos::ByteSizeLong,
              &P2SBoatPositioningSysUpdatePos::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
          PROTOBUF_FIELD_OFFSET(P2SBoatPositioningSysUpdatePos, _impl_._cached_size_),
          false,
      },
#ifdef PROTOBUF_MESSAGE_GLOBALS
      &file_reflection_data[4],
#else   // !PROTOBUF_MESSAGE_GLOBALS
      &::_pbi::kDescriptorMethods,
      &descriptor_table_perip2s_2eproto,
      nullptr,  // tracker
#endif  // PROTOBUF_MESSAGE_GLOBALS
  };
}
struct P2SBoatPositioningSysUpdatePosGlobalsTypeInternal : ::_pbi::MessageGlobalsBase {
  constexpr P2SBoatPositioningSysUpdatePosGlobalsTypeInternal()
      :
#ifndef PROTOBUF_MESSAGE_GLOBALS
        _default(::_pbi::ConstantInitialized{},
                 P2SBoatPositioningSysUpdatePos_class_data_.base())
#else   // !PROTOBUF_MESSAGE_GLOBALS
        MessageGlobalsBase(P2SBoatPositioningSysUpdatePos::InternalGenerateClassData_(
            _default, &P2SBoatPositioningSysUpdatePos_globals_._table.header)),
        _default(::_pbi::ConstantInitialized{}, GetClassData()),
        _table(::_pbi::PrivateAccess::GenerateParseTable<P2SBoatPositioningSysUpdatePos>(
            GetClassData()))
#endif  // PROTOBUF_MESSAGE_GLOBALS
  {
  }
  ~P2SBoatPositioningSysUpdatePosGlobalsTypeInternal() {}
  union {
    alignas(::_pbi::kMaxMessageAlignment) P2SBoatPositioningSysUpdatePos _default;
  };
#ifdef PROTOBUF_MESSAGE_GLOBALS
  decltype(::_pbi::PrivateAccess::GenerateParseTable<P2SBoatPositioningSysUpdatePos>(
      ::std::declval<const ::_pbi::ClassData*>())) _table;
#endif
};
#ifdef PROTOBUF_MESSAGE_GLOBALS
static_assert(PROTOBUF_FIELD_OFFSET(P2SBoatPositioningSysUpdatePosGlobalsTypeInternal, _default) ==
              ::_pbi::MessageGlobalsBase::OffsetToDefault());
#endif  // PROTOBUF_MESSAGE_GLOBALS

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 PROTOBUF_MESSAGE_GLOBALS_CONST P2SBoatPositioningSysUpdatePosGlobalsTypeInternal P2SBoatPositioningSysUpdatePos_globals_
        PROTOBUF_MESSAGE_GLOBALS_SECTION(.data.rel.ro);
#if defined(PROTOBUF_CUSTOM_VTABLE)
namespace {
const ::_pbi::ClassData* P2SBoatPositioningSysUpdatePos_get_class_data() {
#ifdef PROTOBUF_MESSAGE_GLOBALS
  return P2SBoatPositioningSysUpdatePos_globals_.GetClassData();
#else
  return P2SBoatPositioningSysUpdatePos_class_data_.base();
#endif  // PROTOBUF_MESSAGE_GLOBALS
}
}  // namespace
#endif  // PROTOBUF_CUSTOM_VTABLE
}  // namespace proto
}  // namespace peripheral
static const ::_pb::EnumDescriptor* PROTOBUF_NONNULL
    file_level_enum_descriptors_perip2s_2eproto[1];
static constexpr const ::_pb::ServiceDescriptor* PROTOBUF_NONNULL* PROTOBUF_NULLABLE
    file_level_service_descriptors_perip2s_2eproto = nullptr;
const ::uint32_t
    TableStruct_perip2s_2eproto::offsets[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
        protodesc_cold) = {
        0x000, // bitmap
        0x000, // bitmap
        0x081, // bitmap
        PROTOBUF_FIELD_OFFSET(::peripheral::proto::S2PBoatPositioningSysRegister, _impl_._has_bits_),
        4, // hasbit index offset
        PROTOBUF_FIELD_OFFSET(::peripheral::proto::S2PBoatPositioningSysRegister, _impl_.ret_),
        0,
        0x081, // bitmap
        PROTOBUF_FIELD_OFFSET(::peripheral::proto::Position, _impl_._has_bits_),
        6, // hasbit index offset
        PROTOBUF_FIELD_OFFSET(::peripheral::proto::Position, _impl_.x_),
        PROTOBUF_FIELD_OFFSET(::peripheral::proto::Position, _impl_.y_),
        PROTOBUF_FIELD_OFFSET(::peripheral::proto::Position, _impl_.z_),
        0,
        1,
        2,
        0x081, // bitmap
        PROTOBUF_FIELD_OFFSET(::peripheral::proto::P2SBoatPositioningSysUpdatePos, _impl_._has_bits_),
        6, // hasbit index offset
        PROTOBUF_FIELD_OFFSET(::peripheral::proto::P2SBoatPositioningSysUpdatePos, _impl_.boat_id_),
        PROTOBUF_FIELD_OFFSET(::peripheral::proto::P2SBoatPositioningSysUpdatePos, _impl_.pos_),
        PROTOBUF_FIELD_OFFSET(::peripheral::proto::P2SBoatPositioningSysUpdatePos, _impl_.timestamp_),
        2,
        0,
        1,
        0x081, // bitmap
        PROTOBUF_FIELD_OFFSET(::peripheral::proto::P2SBoatPositioningSysUpdatePoint, _impl_._has_bits_),
        6, // hasbit index offset
        PROTOBUF_FIELD_OFFSET(::peripheral::proto::P2SBoatPositioningSysUpdatePoint, _impl_.boat_id_),
        PROTOBUF_FIELD_OFFSET(::peripheral::proto::P2SBoatPositioningSysUpdatePoint, _impl_.point_id_),
        PROTOBUF_FIELD_OFFSET(::peripheral::proto::P2SBoatPositioningSysUpdatePoint, _impl_.timestamp_),
        0,
        1,
        2,
};

static const ::_pbi::MigrationSchema
    schemas[] ABSL_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
        {0, sizeof(::peripheral::proto::Heartbeat)},
        {1, sizeof(::peripheral::proto::P2SBoatPositioningSysRegister)},
        {2, sizeof(::peripheral::proto::S2PBoatPositioningSysRegister)},
        {7, sizeof(::peripheral::proto::Position)},
        {16, sizeof(::peripheral::proto::P2SBoatPositioningSysUpdatePos)},
        {25, sizeof(::peripheral::proto::P2SBoatPositioningSysUpdatePoint)},
};
static const ::_pbi::MessageGlobalsBase* PROTOBUF_NONNULL const
    file_message_globals[] = {
        &::peripheral::proto::Heartbeat_globals_,
        &::peripheral::proto::P2SBoatPositioningSysRegister_globals_,
        &::peripheral::proto::S2PBoatPositioningSysRegister_globals_,
        &::peripheral::proto::Position_globals_,
        &::peripheral::proto::P2SBoatPositioningSysUpdatePos_globals_,
        &::peripheral::proto::P2SBoatPositioningSysUpdatePoint_globals_,
};
const char descriptor_table_protodef_perip2s_2eproto[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
    protodesc_cold) = {
    "\n\rperip2s.proto\022\020peripheral.proto\"\013\n\tHea"
    "rtbeat\"\037\n\035P2SBoatPositioningSysRegister\""
    ",\n\035S2PBoatPositioningSysRegister\022\013\n\003ret\030"
    "\001 \001(\005\"+\n\010Position\022\t\n\001x\030\001 \001(\002\022\t\n\001y\030\002 \001(\002\022"
    "\t\n\001z\030\003 \001(\002\"m\n\036P2SBoatPositioningSysUpdat"
    "ePos\022\017\n\007boat_id\030\001 \001(\005\022\'\n\003pos\030\002 \001(\0132\032.per"
    "ipheral.proto.Position\022\021\n\ttimestamp\030\003 \001("
    "\003\"X\n P2SBoatPositioningSysUpdatePoint\022\017\n"
    "\007boat_id\030\001 \001(\005\022\020\n\010point_id\030\002 \001(\005\022\021\n\ttime"
    "stamp\030\003 \001(\003*\313\002\n\007CmdType\022\013\n\007CMD_MIN\020\000\022\021\n\r"
    "CMD_HEARTBEAT\020\001\022\031\n\024CMD_PERIP2SERVER_MIN\020"
    "\301\014\022*\n%CMD_P2S_BOAT_POSITIONING_SYS_REGIS"
    "TER\020\302\014\022,\n\'CMD_P2S_BOAT_POSITIONING_SYS_U"
    "PDATE_POS\020\303\014\022.\n)CMD_P2S_BOAT_POSITIONING"
    "_SYS_UPDATE_POINT\020\304\014\022\031\n\024CMD_PERIP2SERVER"
    "_MAX\020\244\r\022\031\n\024CMD_SERVER2PERIP_MIN\020\245\r\022*\n%CM"
    "D_S2P_BOAT_POSITIONING_SYS_REGISTER\020\246\r\022\031"
    "\n\024CMD_SERVER2PERIP_MAX\020\210\016b\006proto3"
};
static ::absl::once_flag descriptor_table_perip2s_2eproto_once;
PROTOBUF_CONSTINIT const ::_pbi::DescriptorTable descriptor_table_perip2s_2eproto = {
    false,
    false,
    713,
    descriptor_table_protodef_perip2s_2eproto,
    "perip2s.proto",
    &descriptor_table_perip2s_2eproto_once,
    nullptr,
    0,
    6,
    schemas,
    file_message_globals,
    TableStruct_perip2s_2eproto::offsets,
    file_level_enum_descriptors_perip2s_2eproto,
    file_level_service_descriptors_perip2s_2eproto,
};
namespace peripheral {
namespace proto {
[[nodiscard]] const ::google::protobuf::EnumDescriptor* PROTOBUF_NONNULL
CmdType_descriptor() {
  ::google::protobuf::internal::AssignDescriptors(&descriptor_table_perip2s_2eproto);
  return file_level_enum_descriptors_perip2s_2eproto[0];
}
PROTOBUF_CONSTINIT const uint32_t CmdType_internal_data_[] = {
    131072u, 524288u, 1700u, 1603u, 1702u, 1602u, 1604u, 1701u, 1800u, 1601u, };
// ===================================================================

Heartbeat::Heartbeat(::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::internal::ZeroFieldsBase(arena, Heartbeat_get_class_data()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::internal::ZeroFieldsBase(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  // @@protoc_insertion_point(arena_constructor:peripheral.proto.Heartbeat)
}
Heartbeat::Heartbeat(
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena,
    const Heartbeat& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::internal::ZeroFieldsBase(arena, Heartbeat_get_class_data()) {

#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::internal::ZeroFieldsBase(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  Heartbeat* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);

  // @@protoc_insertion_point(copy_constructor:peripheral.proto.Heartbeat)
}

#ifndef PROTOBUF_MESSAGE_GLOBALS
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 const
    ::google::protobuf::internal::ClassDataFull Heartbeat_class_data_ =
        Heartbeat::InternalGenerateClassData_(Heartbeat_globals_._default);

PROTOBUF_ATTRIBUTE_WEAK const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL
Heartbeat::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&Heartbeat_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(Heartbeat_class_data_.tc_table);
  return Heartbeat_class_data_.base();
}
#else
PROTOBUF_ATTRIBUTE_WEAK const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL
Heartbeat::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&Heartbeat_globals_);
  ::google::protobuf::internal::PrefetchToLocalCache(
      ::google::protobuf::internal::MessageGlobalsBase::ToParseTableBase(&Heartbeat_globals_));
  return Heartbeat_globals_.GetClassData();
}
#endif  // !PROTOBUF_MESSAGE_GLOBALS
#ifndef PROTOBUF_MESSAGE_GLOBALS
PROTOBUF_CONSTINIT
PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 const Heartbeat::ParseTableT_
    Heartbeat::_table_ =
        Heartbeat::InternalGenerateParseTable_(Heartbeat_class_data_.base());
#endif  // !PROTOBUF_MESSAGE_GLOBALS







::google::protobuf::Metadata Heartbeat::GetMetadata() const {
  return ::google::protobuf::internal::ZeroFieldsBase::GetMetadataImpl(GetClassData()->full());
}
// ===================================================================

P2SBoatPositioningSysRegister::P2SBoatPositioningSysRegister(::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::internal::ZeroFieldsBase(arena, P2SBoatPositioningSysRegister_get_class_data()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::internal::ZeroFieldsBase(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  // @@protoc_insertion_point(arena_constructor:peripheral.proto.P2SBoatPositioningSysRegister)
}
P2SBoatPositioningSysRegister::P2SBoatPositioningSysRegister(
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena,
    const P2SBoatPositioningSysRegister& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::internal::ZeroFieldsBase(arena, P2SBoatPositioningSysRegister_get_class_data()) {

#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::internal::ZeroFieldsBase(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  P2SBoatPositioningSysRegister* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);

  // @@protoc_insertion_point(copy_constructor:peripheral.proto.P2SBoatPositioningSysRegister)
}

#ifndef PROTOBUF_MESSAGE_GLOBALS
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 const
    ::google::protobuf::internal::ClassDataFull P2SBoatPositioningSysRegister_class_data_ =
        P2SBoatPositioningSysRegister::InternalGenerateClassData_(P2SBoatPositioningSysRegister_globals_._default);

PROTOBUF_ATTRIBUTE_WEAK const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL
P2SBoatPositioningSysRegister::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&P2SBoatPositioningSysRegister_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(P2SBoatPositioningSysRegister_class_data_.tc_table);
  return P2SBoatPositioningSysRegister_class_data_.base();
}
#else
PROTOBUF_ATTRIBUTE_WEAK const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL
P2SBoatPositioningSysRegister::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&P2SBoatPositioningSysRegister_globals_);
  ::google::protobuf::internal::PrefetchToLocalCache(
      ::google::protobuf::internal::MessageGlobalsBase::ToParseTableBase(&P2SBoatPositioningSysRegister_globals_));
  return P2SBoatPositioningSysRegister_globals_.GetClassData();
}
#endif  // !PROTOBUF_MESSAGE_GLOBALS
#ifndef PROTOBUF_MESSAGE_GLOBALS
PROTOBUF_CONSTINIT
PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 const P2SBoatPositioningSysRegister::ParseTableT_
    P2SBoatPositioningSysRegister::_table_ =
        P2SBoatPositioningSysRegister::InternalGenerateParseTable_(P2SBoatPositioningSysRegister_class_data_.base());
#endif  // !PROTOBUF_MESSAGE_GLOBALS







::google::protobuf::Metadata P2SBoatPositioningSysRegister::GetMetadata() const {
  return ::google::protobuf::internal::ZeroFieldsBase::GetMetadataImpl(GetClassData()->full());
}
// ===================================================================

S2PBoatPositioningSysRegister::S2PBoatPositioningSysRegister(::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, S2PBoatPositioningSysRegister_get_class_data()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:peripheral.proto.S2PBoatPositioningSysRegister)
}
S2PBoatPositioningSysRegister::S2PBoatPositioningSysRegister(
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const S2PBoatPositioningSysRegister& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, S2PBoatPositioningSysRegister_get_class_data()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(from._impl_) {
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
}
PROTOBUF_NDEBUG_INLINE S2PBoatPositioningSysRegister::Impl_::Impl_(
    [[maybe_unused]] ::google::protobuf::internal::InternalVisibility visibility,
    [[maybe_unused]] ::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
      : _cached_size_{0} {}

inline void S2PBoatPositioningSysRegister::SharedCtor(::_pb::Arena* PROTOBUF_NULLABLE arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  _impl_.ret_ = {};
}
S2PBoatPositioningSysRegister::~S2PBoatPositioningSysRegister() {
  // @@protoc_insertion_point(destructor:peripheral.proto.S2PBoatPositioningSysRegister)
  SharedDtor(*this);
}
inline void S2PBoatPositioningSysRegister::SharedDtor(MessageLite& self) {
  S2PBoatPositioningSysRegister& this_ = static_cast<S2PBoatPositioningSysRegister&>(self);
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    this_.CheckHasBitConsistency();
  }
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.~Impl_();
}

#ifndef PROTOBUF_MESSAGE_GLOBALS
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 const
    ::google::protobuf::internal::ClassDataFull S2PBoatPositioningSysRegister_class_data_ =
        S2PBoatPositioningSysRegister::InternalGenerateClassData_(S2PBoatPositioningSysRegister_globals_._default);

PROTOBUF_ATTRIBUTE_WEAK const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL
S2PBoatPositioningSysRegister::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&S2PBoatPositioningSysRegister_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(S2PBoatPositioningSysRegister_class_data_.tc_table);
  return S2PBoatPositioningSysRegister_class_data_.base();
}
#else
PROTOBUF_ATTRIBUTE_WEAK const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL
S2PBoatPositioningSysRegister::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&S2PBoatPositioningSysRegister_globals_);
  ::google::protobuf::internal::PrefetchToLocalCache(
      ::google::protobuf::internal::MessageGlobalsBase::ToParseTableBase(&S2PBoatPositioningSysRegister_globals_));
  return S2PBoatPositioningSysRegister_globals_.GetClassData();
}
#endif  // !PROTOBUF_MESSAGE_GLOBALS
#ifndef PROTOBUF_MESSAGE_GLOBALS
PROTOBUF_CONSTINIT
PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 const S2PBoatPositioningSysRegister::ParseTableT_
    S2PBoatPositioningSysRegister::_table_ =
        S2PBoatPositioningSysRegister::InternalGenerateParseTable_(S2PBoatPositioningSysRegister_class_data_.base());
#endif  // !PROTOBUF_MESSAGE_GLOBALS
PROTOBUF_NOINLINE void S2PBoatPositioningSysRegister::Clear() {
// @@protoc_insertion_point(message_clear_start:peripheral.proto.S2PBoatPositioningSysRegister)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.ret_ = 0;
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::uint8_t* PROTOBUF_NONNULL S2PBoatPositioningSysRegister::_InternalSerialize(
    const ::google::protobuf::MessageLite& base, ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) {
  const S2PBoatPositioningSysRegister& this_ = static_cast<const S2PBoatPositioningSysRegister&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::uint8_t* PROTOBUF_NONNULL S2PBoatPositioningSysRegister::_InternalSerialize(
    ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
  const S2PBoatPositioningSysRegister& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    this_.CheckHasBitConsistency();
  }
  // @@protoc_insertion_point(serialize_to_array_start:peripheral.proto.S2PBoatPositioningSysRegister)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  cached_has_bits = this_._impl_._has_bits_[0];
  // int32 ret = 1;
  if (CheckHasBit(cached_has_bits, 0x00000001U)) {
    if (this_._internal_ret() != 0) {
      target =
          ::google::protobuf::internal::WireFormatLite::WriteInt32ToArrayWithField<1>(
              stream, this_._internal_ret(), target);
    }
  }

  if (ABSL_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:peripheral.proto.S2PBoatPositioningSysRegister)
  return target;
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::size_t S2PBoatPositioningSysRegister::ByteSizeLong(const MessageLite& base) {
  const S2PBoatPositioningSysRegister& this_ = static_cast<const S2PBoatPositioningSysRegister&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::size_t S2PBoatPositioningSysRegister::ByteSizeLong() const {
  const S2PBoatPositioningSysRegister& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  // @@protoc_insertion_point(message_byte_size_start:peripheral.proto.S2PBoatPositioningSysRegister)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void)cached_has_bits;

   {
    // int32 ret = 1;
    cached_has_bits = this_._impl_._has_bits_[0];
    if (CheckHasBit(cached_has_bits, 0x00000001U)) {
      if (this_._internal_ret() != 0) {
        total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(
            this_._internal_ret());
      }
    }
  }
  return this_.MaybeComputeUnknownFieldsSize(total_size,
                                             &this_._impl_._cached_size_);
}

void S2PBoatPositioningSysRegister::MergeImpl(::google::protobuf::MessageLite& to_msg,
                      const ::google::protobuf::MessageLite& from_msg) {
   auto* const _this = static_cast<S2PBoatPositioningSysRegister*>(&to_msg);
  auto& from = static_cast<const S2PBoatPositioningSysRegister&>(from_msg);
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    from.CheckHasBitConsistency();
  }
  // @@protoc_insertion_point(class_specific_merge_from_start:peripheral.proto.S2PBoatPositioningSysRegister)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  cached_has_bits = from._impl_._has_bits_[0];
  if (CheckHasBit(cached_has_bits, 0x00000001U)) {
    if (from._internal_ret() != 0) {
      _this->_impl_.ret_ = from._impl_.ret_;
    }
  }
  _this->_impl_._has_bits_[0] |= cached_has_bits;
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
}

void S2PBoatPositioningSysRegister::CopyFrom(const S2PBoatPositioningSysRegister& from) {
  // @@protoc_insertion_point(class_specific_copy_from_start:peripheral.proto.S2PBoatPositioningSysRegister)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void S2PBoatPositioningSysRegister::InternalSwap(S2PBoatPositioningSysRegister* PROTOBUF_RESTRICT PROTOBUF_NONNULL other) {
  using ::std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  swap(_impl_.ret_, other->_impl_.ret_);
}

::google::protobuf::Metadata S2PBoatPositioningSysRegister::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// ===================================================================

Position::Position(::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, Position_get_class_data()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:peripheral.proto.Position)
}
Position::Position(
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Position& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, Position_get_class_data()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(from._impl_) {
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
}
PROTOBUF_NDEBUG_INLINE Position::Impl_::Impl_(
    [[maybe_unused]] ::google::protobuf::internal::InternalVisibility visibility,
    [[maybe_unused]] ::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
      : _cached_size_{0} {}

inline void Position::SharedCtor(::_pb::Arena* PROTOBUF_NULLABLE arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  ::memset(reinterpret_cast<char*>(&_impl_) +
               offsetof(Impl_, x_),
           0,
           offsetof(Impl_, z_) -
               offsetof(Impl_, x_) +
               sizeof(Impl_::z_));
}
Position::~Position() {
  // @@protoc_insertion_point(destructor:peripheral.proto.Position)
  SharedDtor(*this);
}
inline void Position::SharedDtor(MessageLite& self) {
  Position& this_ = static_cast<Position&>(self);
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    this_.CheckHasBitConsistency();
  }
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.~Impl_();
}

#ifndef PROTOBUF_MESSAGE_GLOBALS
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 const
    ::google::protobuf::internal::ClassDataFull Position_class_data_ =
        Position::InternalGenerateClassData_(Position_globals_._default);

PROTOBUF_ATTRIBUTE_WEAK const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL
Position::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&Position_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(Position_class_data_.tc_table);
  return Position_class_data_.base();
}
#else
PROTOBUF_ATTRIBUTE_WEAK const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL
Position::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&Position_globals_);
  ::google::protobuf::internal::PrefetchToLocalCache(
      ::google::protobuf::internal::MessageGlobalsBase::ToParseTableBase(&Position_globals_));
  return Position_globals_.GetClassData();
}
#endif  // !PROTOBUF_MESSAGE_GLOBALS
#ifndef PROTOBUF_MESSAGE_GLOBALS
PROTOBUF_CONSTINIT
PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 const Position::ParseTableT_
    Position::_table_ =
        Position::InternalGenerateParseTable_(Position_class_data_.base());
#endif  // !PROTOBUF_MESSAGE_GLOBALS
PROTOBUF_NOINLINE void Position::Clear() {
// @@protoc_insertion_point(message_clear_start:peripheral.proto.Position)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  if (BatchCheckHasBit(cached_has_bits, 0x00000007U)) {
    ::memset(&_impl_.x_, 0, static_cast<::size_t>(
        reinterpret_cast<char*>(&_impl_.z_) -
        reinterpret_cast<char*>(&_impl_.x_)) + sizeof(_impl_.z_));
  }
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::uint8_t* PROTOBUF_NONNULL Position::_InternalSerialize(
    const ::google::protobuf::MessageLite& base, ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) {
  const Position& this_ = static_cast<const Position&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::uint8_t* PROTOBUF_NONNULL Position::_InternalSerialize(
    ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
  const Position& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    this_.CheckHasBitConsistency();
  }
  // @@protoc_insertion_point(serialize_to_array_start:peripheral.proto.Position)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  cached_has_bits = this_._impl_._has_bits_[0];
  // float x = 1;
  if (CheckHasBit(cached_has_bits, 0x00000001U)) {
    if (::absl::bit_cast<::uint32_t>(this_._internal_x()) != 0) {
      target = stream->EnsureSpace(target);
      target = ::_pbi::WireFormatLite::WriteFloatToArray(
          1, this_._internal_x(), target);
    }
  }

  // float y = 2;
  if (CheckHasBit(cached_has_bits, 0x00000002U)) {
    if (::absl::bit_cast<::uint32_t>(this_._internal_y()) != 0) {
      target = stream->EnsureSpace(target);
      target = ::_pbi::WireFormatLite::WriteFloatToArray(
          2, this_._internal_y(), target);
    }
  }

  // float z = 3;
  if (CheckHasBit(cached_has_bits, 0x00000004U)) {
    if (::absl::bit_cast<::uint32_t>(this_._internal_z()) != 0) {
      target = stream->EnsureSpace(target);
      target = ::_pbi::WireFormatLite::WriteFloatToArray(
          3, this_._internal_z(), target);
    }
  }

  if (ABSL_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:peripheral.proto.Position)
  return target;
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::size_t Position::ByteSizeLong(const MessageLite& base) {
  const Position& this_ = static_cast<const Position&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::size_t Position::ByteSizeLong() const {
  const Position& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  // @@protoc_insertion_point(message_byte_size_start:peripheral.proto.Position)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void)cached_has_bits;

  ::_pbi::Prefetch5LinesFrom7Lines(&this_);
  cached_has_bits = this_._impl_._has_bits_[0];
  if (BatchCheckHasBit(cached_has_bits, 0x00000007U)) {
    // float x = 1;
    if (CheckHasBit(cached_has_bits, 0x00000001U)) {
      if (::absl::bit_cast<::uint32_t>(this_._internal_x()) != 0) {
        total_size += 5;
      }
    }
    // float y = 2;
    if (CheckHasBit(cached_has_bits, 0x00000002U)) {
      if (::absl::bit_cast<::uint32_t>(this_._internal_y()) != 0) {
        total_size += 5;
      }
    }
    // float z = 3;
    if (CheckHasBit(cached_has_bits, 0x00000004U)) {
      if (::absl::bit_cast<::uint32_t>(this_._internal_z()) != 0) {
        total_size += 5;
      }
    }
  }
  return this_.MaybeComputeUnknownFieldsSize(total_size,
                                             &this_._impl_._cached_size_);
}

void Position::MergeImpl(::google::protobuf::MessageLite& to_msg,
                      const ::google::protobuf::MessageLite& from_msg) {
   auto* const _this = static_cast<Position*>(&to_msg);
  auto& from = static_cast<const Position&>(from_msg);
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    from.CheckHasBitConsistency();
  }
  // @@protoc_insertion_point(class_specific_merge_from_start:peripheral.proto.Position)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  cached_has_bits = from._impl_._has_bits_[0];
  if (BatchCheckHasBit(cached_has_bits, 0x00000007U)) {
    if (CheckHasBit(cached_has_bits, 0x00000001U)) {
      if (::absl::bit_cast<::uint32_t>(from._internal_x()) != 0) {
        _this->_impl_.x_ = from._impl_.x_;
      }
    }
    if (CheckHasBit(cached_has_bits, 0x00000002U)) {
      if (::absl::bit_cast<::uint32_t>(from._internal_y()) != 0) {
        _this->_impl_.y_ = from._impl_.y_;
      }
    }
    if (CheckHasBit(cached_has_bits, 0x00000004U)) {
      if (::absl::bit_cast<::uint32_t>(from._internal_z()) != 0) {
        _this->_impl_.z_ = from._impl_.z_;
      }
    }
  }
  _this->_impl_._has_bits_[0] |= cached_has_bits;
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
}

void Position::CopyFrom(const Position& from) {
  // @@protoc_insertion_point(class_specific_copy_from_start:peripheral.proto.Position)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void Position::InternalSwap(Position* PROTOBUF_RESTRICT PROTOBUF_NONNULL other) {
  using ::std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  ::google::protobuf::internal::memswap<
      PROTOBUF_FIELD_OFFSET(Position, _impl_.z_)
      + sizeof(Position::_impl_.z_)
      - PROTOBUF_FIELD_OFFSET(Position, _impl_.x_)>(
          reinterpret_cast<char*>(&_impl_.x_),
          reinterpret_cast<char*>(&other->_impl_.x_));
}

::google::protobuf::Metadata Position::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// ===================================================================

P2SBoatPositioningSysUpdatePos::P2SBoatPositioningSysUpdatePos(::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, P2SBoatPositioningSysUpdatePos_get_class_data()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:peripheral.proto.P2SBoatPositioningSysUpdatePos)
}
PROTOBUF_NDEBUG_INLINE P2SBoatPositioningSysUpdatePos::Impl_::Impl_(
    [[maybe_unused]] ::google::protobuf::internal::InternalVisibility visibility,
    [[maybe_unused]] ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
    [[maybe_unused]] const ::peripheral::proto::P2SBoatPositioningSysUpdatePos& from_msg)
      : _has_bits_{from._has_bits_},
        _cached_size_{0} {}

P2SBoatPositioningSysUpdatePos::P2SBoatPositioningSysUpdatePos(
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena,
    const P2SBoatPositioningSysUpdatePos& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, P2SBoatPositioningSysUpdatePos_get_class_data()) {

#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  P2SBoatPositioningSysUpdatePos* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);
  ::uint32_t cached_has_bits = _impl_._has_bits_[0];
  _impl_.pos_ = (CheckHasBit(cached_has_bits, 0x00000001U))
                ? ::google::protobuf::Message::CopyConstruct(arena, *from._impl_.pos_)
                : nullptr;
  ::memcpy(reinterpret_cast<char*>(&_impl_) +
               offsetof(Impl_, timestamp_),
           reinterpret_cast<const char*>(&from._impl_) +
               offsetof(Impl_, timestamp_),
           offsetof(Impl_, boat_id_) -
               offsetof(Impl_, timestamp_) +
               sizeof(Impl_::boat_id_));

  // @@protoc_insertion_point(copy_constructor:peripheral.proto.P2SBoatPositioningSysUpdatePos)
}
PROTOBUF_NDEBUG_INLINE P2SBoatPositioningSysUpdatePos::Impl_::Impl_(
    [[maybe_unused]] ::google::protobuf::internal::InternalVisibility visibility,
    [[maybe_unused]] ::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
      : _cached_size_{0} {}

inline void P2SBoatPositioningSysUpdatePos::SharedCtor(::_pb::Arena* PROTOBUF_NULLABLE arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  ::memset(reinterpret_cast<char*>(&_impl_) +
               offsetof(Impl_, pos_),
           0,
           offsetof(Impl_, boat_id_) -
               offsetof(Impl_, pos_) +
               sizeof(Impl_::boat_id_));
}
P2SBoatPositioningSysUpdatePos::~P2SBoatPositioningSysUpdatePos() {
  // @@protoc_insertion_point(destructor:peripheral.proto.P2SBoatPositioningSysUpdatePos)
  SharedDtor(*this);
}
inline void P2SBoatPositioningSysUpdatePos::SharedDtor(MessageLite& self) {
  P2SBoatPositioningSysUpdatePos& this_ = static_cast<P2SBoatPositioningSysUpdatePos&>(self);
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    this_.CheckHasBitConsistency();
  }
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  delete this_._impl_.pos_;
  this_._impl_.~Impl_();
}

#ifndef PROTOBUF_MESSAGE_GLOBALS
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 const
    ::google::protobuf::internal::ClassDataFull P2SBoatPositioningSysUpdatePos_class_data_ =
        P2SBoatPositioningSysUpdatePos::InternalGenerateClassData_(P2SBoatPositioningSysUpdatePos_globals_._default);

PROTOBUF_ATTRIBUTE_WEAK const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL
P2SBoatPositioningSysUpdatePos::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&P2SBoatPositioningSysUpdatePos_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(P2SBoatPositioningSysUpdatePos_class_data_.tc_table);
  return P2SBoatPositioningSysUpdatePos_class_data_.base();
}
#else
PROTOBUF_ATTRIBUTE_WEAK const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL
P2SBoatPositioningSysUpdatePos::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&P2SBoatPositioningSysUpdatePos_globals_);
  ::google::protobuf::internal::PrefetchToLocalCache(
      ::google::protobuf::internal::MessageGlobalsBase::ToParseTableBase(&P2SBoatPositioningSysUpdatePos_globals_));
  return P2SBoatPositioningSysUpdatePos_globals_.GetClassData();
}
#endif  // !PROTOBUF_MESSAGE_GLOBALS
#ifndef PROTOBUF_MESSAGE_GLOBALS
PROTOBUF_CONSTINIT
PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 const P2SBoatPositioningSysUpdatePos::ParseTableT_
    P2SBoatPositioningSysUpdatePos::_table_ =
        P2SBoatPositioningSysUpdatePos::InternalGenerateParseTable_(P2SBoatPositioningSysUpdatePos_class_data_.base());
#endif  // !PROTOBUF_MESSAGE_GLOBALS
PROTOBUF_NOINLINE void P2SBoatPositioningSysUpdatePos::Clear() {
// @@protoc_insertion_point(message_clear_start:peripheral.proto.P2SBoatPositioningSysUpdatePos)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  if (CheckHasBit(cached_has_bits, 0x00000001U)) {
    ABSL_DCHECK(_impl_.pos_ != nullptr);
    _impl_.pos_->Clear();
  }
  if (BatchCheckHasBit(cached_has_bits, 0x00000006U)) {
    ::memset(&_impl_.timestamp_, 0, static_cast<::size_t>(
        reinterpret_cast<char*>(&_impl_.boat_id_) -
        reinterpret_cast<char*>(&_impl_.timestamp_)) + sizeof(_impl_.boat_id_));
  }
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::uint8_t* PROTOBUF_NONNULL P2SBoatPositioningSysUpdatePos::_InternalSerialize(
    const ::google::protobuf::MessageLite& base, ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) {
  const P2SBoatPositioningSysUpdatePos& this_ = static_cast<const P2SBoatPositioningSysUpdatePos&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::uint8_t* PROTOBUF_NONNULL P2SBoatPositioningSysUpdatePos::_InternalSerialize(
    ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
  const P2SBoatPositioningSysUpdatePos& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    this_.CheckHasBitConsistency();
  }
  // @@protoc_insertion_point(serialize_to_array_start:peripheral.proto.P2SBoatPositioningSysUpdatePos)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  cached_has_bits = this_._impl_._has_bits_[0];
  // int32 boat_id = 1;
  if (CheckHasBit(cached_has_bits, 0x00000004U)) {
    if (this_._internal_boat_id() != 0) {
      target =
          ::google::protobuf::internal::WireFormatLite::WriteInt32ToArrayWithField<1>(
              stream, this_._internal_boat_id(), target);
    }
  }

  // .peripheral.proto.Position pos = 2;
  if (CheckHasBit(cached_has_bits, 0x00000001U)) {
    target = ::google::protobuf::internal::WireFormatLite::InternalWriteMessage(
        2, *this_._impl_.pos_, this_._impl_.pos_->GetCachedSize(), target,
        stream);
  }

  // int64 timestamp = 3;
  if (CheckHasBit(cached_has_bits, 0x00000002U)) {
    if (this_._internal_timestamp() != 0) {
      target =
          ::google::protobuf::internal::WireFormatLite::WriteInt64ToArrayWithField<3>(
              stream, this_._internal_timestamp(), target);
    }
  }

  if (ABSL_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:peripheral.proto.P2SBoatPositioningSysUpdatePos)
  return target;
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::size_t P2SBoatPositioningSysUpdatePos::ByteSizeLong(const MessageLite& base) {
  const P2SBoatPositioningSysUpdatePos& this_ = static_cast<const P2SBoatPositioningSysUpdatePos&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::size_t P2SBoatPositioningSysUpdatePos::ByteSizeLong() const {
  const P2SBoatPositioningSysUpdatePos& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  // @@protoc_insertion_point(message_byte_size_start:peripheral.proto.P2SBoatPositioningSysUpdatePos)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void)cached_has_bits;

  ::_pbi::Prefetch5LinesFrom7Lines(&this_);
  cached_has_bits = this_._impl_._has_bits_[0];
  if (BatchCheckHasBit(cached_has_bits, 0x00000007U)) {
    // .peripheral.proto.Position pos = 2;
    if (CheckHasBit(cached_has_bits, 0x00000001U)) {
      total_size += 1 +
                    ::google::protobuf::internal::WireFormatLite::MessageSize(*this_._impl_.pos_);
    }
    // int64 timestamp = 3;
    if (CheckHasBit(cached_has_bits, 0x00000002U)) {
      if (this_._internal_timestamp() != 0) {
        total_size += ::_pbi::WireFormatLite::Int64SizePlusOne(
            this_._internal_timestamp());
      }
    }
    // int32 boat_id = 1;
    if (CheckHasBit(cached_has_bits, 0x00000004U)) {
      if (this_._internal_boat_id() != 0) {
        total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(
            this_._internal_boat_id());
      }
    }
  }
  return this_.MaybeComputeUnknownFieldsSize(total_size,
                                             &this_._impl_._cached_size_);
}

void P2SBoatPositioningSysUpdatePos::MergeImpl(::google::protobuf::MessageLite& to_msg,
                      const ::google::protobuf::MessageLite& from_msg) {
   auto* const _this = static_cast<P2SBoatPositioningSysUpdatePos*>(&to_msg);
  auto& from = static_cast<const P2SBoatPositioningSysUpdatePos&>(from_msg);
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    from.CheckHasBitConsistency();
  }
  ::google::protobuf::Arena* arena = _this->GetArena();
  // @@protoc_insertion_point(class_specific_merge_from_start:peripheral.proto.P2SBoatPositioningSysUpdatePos)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  cached_has_bits = from._impl_._has_bits_[0];
  if (BatchCheckHasBit(cached_has_bits, 0x00000007U)) {
    if (CheckHasBit(cached_has_bits, 0x00000001U)) {
      ABSL_DCHECK(from._impl_.pos_ != nullptr);
      if (_this->_impl_.pos_ == nullptr) {
        _this->_impl_.pos_ = ::google::protobuf::Message::CopyConstruct(arena, *from._impl_.pos_);
      } else {
        _this->_impl_.pos_->MergeFrom(*from._impl_.pos_);
      }
    }
    if (CheckHasBit(cached_has_bits, 0x00000002U)) {
      if (from._internal_timestamp() != 0) {
        _this->_impl_.timestamp_ = from._impl_.timestamp_;
      }
    }
    if (CheckHasBit(cached_has_bits, 0x00000004U)) {
      if (from._internal_boat_id() != 0) {
        _this->_impl_.boat_id_ = from._impl_.boat_id_;
      }
    }
  }
  _this->_impl_._has_bits_[0] |= cached_has_bits;
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
}

void P2SBoatPositioningSysUpdatePos::CopyFrom(const P2SBoatPositioningSysUpdatePos& from) {
  // @@protoc_insertion_point(class_specific_copy_from_start:peripheral.proto.P2SBoatPositioningSysUpdatePos)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void P2SBoatPositioningSysUpdatePos::InternalSwap(P2SBoatPositioningSysUpdatePos* PROTOBUF_RESTRICT PROTOBUF_NONNULL other) {
  using ::std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  ::google::protobuf::internal::memswap<
      PROTOBUF_FIELD_OFFSET(P2SBoatPositioningSysUpdatePos, _impl_.boat_id_)
      + sizeof(P2SBoatPositioningSysUpdatePos::_impl_.boat_id_)
      - PROTOBUF_FIELD_OFFSET(P2SBoatPositioningSysUpdatePos, _impl_.pos_)>(
          reinterpret_cast<char*>(&_impl_.pos_),
          reinterpret_cast<char*>(&other->_impl_.pos_));
}

::google::protobuf::Metadata P2SBoatPositioningSysUpdatePos::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// ===================================================================

P2SBoatPositioningSysUpdatePoint::P2SBoatPositioningSysUpdatePoint(::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, P2SBoatPositioningSysUpdatePoint_get_class_data()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:peripheral.proto.P2SBoatPositioningSysUpdatePoint)
}
P2SBoatPositioningSysUpdatePoint::P2SBoatPositioningSysUpdatePoint(
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const P2SBoatPositioningSysUpdatePoint& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, P2SBoatPositioningSysUpdatePoint_get_class_data()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(from._impl_) {
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
}
PROTOBUF_NDEBUG_INLINE P2SBoatPositioningSysUpdatePoint::Impl_::Impl_(
    [[maybe_unused]] ::google::protobuf::internal::InternalVisibility visibility,
    [[maybe_unused]] ::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
      : _cached_size_{0} {}

inline void P2SBoatPositioningSysUpdatePoint::SharedCtor(::_pb::Arena* PROTOBUF_NULLABLE arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  ::memset(reinterpret_cast<char*>(&_impl_) +
               offsetof(Impl_, boat_id_),
           0,
           offsetof(Impl_, timestamp_) -
               offsetof(Impl_, boat_id_) +
               sizeof(Impl_::timestamp_));
}
P2SBoatPositioningSysUpdatePoint::~P2SBoatPositioningSysUpdatePoint() {
  // @@protoc_insertion_point(destructor:peripheral.proto.P2SBoatPositioningSysUpdatePoint)
  SharedDtor(*this);
}
inline void P2SBoatPositioningSysUpdatePoint::SharedDtor(MessageLite& self) {
  P2SBoatPositioningSysUpdatePoint& this_ = static_cast<P2SBoatPositioningSysUpdatePoint&>(self);
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    this_.CheckHasBitConsistency();
  }
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.~Impl_();
}

#ifndef PROTOBUF_MESSAGE_GLOBALS
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 const
    ::google::protobuf::internal::ClassDataFull P2SBoatPositioningSysUpdatePoint_class_data_ =
        P2SBoatPositioningSysUpdatePoint::InternalGenerateClassData_(P2SBoatPositioningSysUpdatePoint_globals_._default);

PROTOBUF_ATTRIBUTE_WEAK const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL
P2SBoatPositioningSysUpdatePoint::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&P2SBoatPositioningSysUpdatePoint_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(P2SBoatPositioningSysUpdatePoint_class_data_.tc_table);
  return P2SBoatPositioningSysUpdatePoint_class_data_.base();
}
#else
PROTOBUF_ATTRIBUTE_WEAK const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL
P2SBoatPositioningSysUpdatePoint::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&P2SBoatPositioningSysUpdatePoint_globals_);
  ::google::protobuf::internal::PrefetchToLocalCache(
      ::google::protobuf::internal::MessageGlobalsBase::ToParseTableBase(&P2SBoatPositioningSysUpdatePoint_globals_));
  return P2SBoatPositioningSysUpdatePoint_globals_.GetClassData();
}
#endif  // !PROTOBUF_MESSAGE_GLOBALS
#ifndef PROTOBUF_MESSAGE_GLOBALS
PROTOBUF_CONSTINIT
PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 const P2SBoatPositioningSysUpdatePoint::ParseTableT_
    P2SBoatPositioningSysUpdatePoint::_table_ =
        P2SBoatPositioningSysUpdatePoint::InternalGenerateParseTable_(P2SBoatPositioningSysUpdatePoint_class_data_.base());
#endif  // !PROTOBUF_MESSAGE_GLOBALS
PROTOBUF_NOINLINE void P2SBoatPositioningSysUpdatePoint::Clear() {
// @@protoc_insertion_point(message_clear_start:peripheral.proto.P2SBoatPositioningSysUpdatePoint)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  if (BatchCheckHasBit(cached_has_bits, 0x00000007U)) {
    ::memset(&_impl_.boat_id_, 0, static_cast<::size_t>(
        reinterpret_cast<char*>(&_impl_.timestamp_) -
        reinterpret_cast<char*>(&_impl_.boat_id_)) + sizeof(_impl_.timestamp_));
  }
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::uint8_t* PROTOBUF_NONNULL P2SBoatPositioningSysUpdatePoint::_InternalSerialize(
    const ::google::protobuf::MessageLite& base, ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) {
  const P2SBoatPositioningSysUpdatePoint& this_ = static_cast<const P2SBoatPositioningSysUpdatePoint&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::uint8_t* PROTOBUF_NONNULL P2SBoatPositioningSysUpdatePoint::_InternalSerialize(
    ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
  const P2SBoatPositioningSysUpdatePoint& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    this_.CheckHasBitConsistency();
  }
  // @@protoc_insertion_point(serialize_to_array_start:peripheral.proto.P2SBoatPositioningSysUpdatePoint)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  cached_has_bits = this_._impl_._has_bits_[0];
  // int32 boat_id = 1;
  if (CheckHasBit(cached_has_bits, 0x00000001U)) {
    if (this_._internal_boat_id() != 0) {
      target =
          ::google::protobuf::internal::WireFormatLite::WriteInt32ToArrayWithField<1>(
              stream, this_._internal_boat_id(), target);
    }
  }

  // int32 point_id = 2;
  if (CheckHasBit(cached_has_bits, 0x00000002U)) {
    if (this_._internal_point_id() != 0) {
      target =
          ::google::protobuf::internal::WireFormatLite::WriteInt32ToArrayWithField<2>(
              stream, this_._internal_point_id(), target);
    }
  }

  // int64 timestamp = 3;
  if (CheckHasBit(cached_has_bits, 0x00000004U)) {
    if (this_._internal_timestamp() != 0) {
      target =
          ::google::protobuf::internal::WireFormatLite::WriteInt64ToArrayWithField<3>(
              stream, this_._internal_timestamp(), target);
    }
  }

  if (ABSL_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:peripheral.proto.P2SBoatPositioningSysUpdatePoint)
  return target;
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::size_t P2SBoatPositioningSysUpdatePoint::ByteSizeLong(const MessageLite& base) {
  const P2SBoatPositioningSysUpdatePoint& this_ = static_cast<const P2SBoatPositioningSysUpdatePoint&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::size_t P2SBoatPositioningSysUpdatePoint::ByteSizeLong() const {
  const P2SBoatPositioningSysUpdatePoint& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  // @@protoc_insertion_point(message_byte_size_start:peripheral.proto.P2SBoatPositioningSysUpdatePoint)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void)cached_has_bits;

  ::_pbi::Prefetch5LinesFrom7Lines(&this_);
  cached_has_bits = this_._impl_._has_bits_[0];
  if (BatchCheckHasBit(cached_has_bits, 0x00000007U)) {
    // int32 boat_id = 1;
    if (CheckHasBit(cached_has_bits, 0x00000001U)) {
      if (this_._internal_boat_id() != 0) {
        total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(
            this_._internal_boat_id());
      }
    }
    // int32 point_id = 2;
    if (CheckHasBit(cached_has_bits, 0x00000002U)) {
      if (this_._internal_point_id() != 0) {
        total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(
            this_._internal_point_id());
      }
    }
    // int64 timestamp = 3;
    if (CheckHasBit(cached_has_bits, 0x00000004U)) {
      if (this_._internal_timestamp() != 0) {
        total_size += ::_pbi::WireFormatLite::Int64SizePlusOne(
            this_._internal_timestamp());
      }
    }
  }
  return this_.MaybeComputeUnknownFieldsSize(total_size,
                                             &this_._impl_._cached_size_);
}

void P2SBoatPositioningSysUpdatePoint::MergeImpl(::google::protobuf::MessageLite& to_msg,
                      const ::google::protobuf::MessageLite& from_msg) {
   auto* const _this = static_cast<P2SBoatPositioningSysUpdatePoint*>(&to_msg);
  auto& from = static_cast<const P2SBoatPositioningSysUpdatePoint&>(from_msg);
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    from.CheckHasBitConsistency();
  }
  // @@protoc_insertion_point(class_specific_merge_from_start:peripheral.proto.P2SBoatPositioningSysUpdatePoint)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  cached_has_bits = from._impl_._has_bits_[0];
  if (BatchCheckHasBit(cached_has_bits, 0x00000007U)) {
    if (CheckHasBit(cached_has_bits, 0x00000001U)) {
      if (from._internal_boat_id() != 0) {
        _this->_impl_.boat_id_ = from._impl_.boat_id_;
      }
    }
    if (CheckHasBit(cached_has_bits, 0x00000002U)) {
      if (from._internal_point_id() != 0) {
        _this->_impl_.point_id_ = from._impl_.point_id_;
      }
    }
    if (CheckHasBit(cached_has_bits, 0x00000004U)) {
      if (from._internal_timestamp() != 0) {
        _this->_impl_.timestamp_ = from._impl_.timestamp_;
      }
    }
  }
  _this->_impl_._has_bits_[0] |= cached_has_bits;
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
}

void P2SBoatPositioningSysUpdatePoint::CopyFrom(const P2SBoatPositioningSysUpdatePoint& from) {
  // @@protoc_insertion_point(class_specific_copy_from_start:peripheral.proto.P2SBoatPositioningSysUpdatePoint)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void P2SBoatPositioningSysUpdatePoint::InternalSwap(P2SBoatPositioningSysUpdatePoint* PROTOBUF_RESTRICT PROTOBUF_NONNULL other) {
  using ::std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  ::google::protobuf::internal::memswap<
      PROTOBUF_FIELD_OFFSET(P2SBoatPositioningSysUpdatePoint, _impl_.timestamp_)
      + sizeof(P2SBoatPositioningSysUpdatePoint::_impl_.timestamp_)
      - PROTOBUF_FIELD_OFFSET(P2SBoatPositioningSysUpdatePoint, _impl_.boat_id_)>(
          reinterpret_cast<char*>(&_impl_.boat_id_),
          reinterpret_cast<char*>(&other->_impl_.boat_id_));
}

::google::protobuf::Metadata P2SBoatPositioningSysUpdatePoint::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// @@protoc_insertion_point(namespace_scope)
}  // namespace proto
}  // namespace peripheral
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google
// @@protoc_insertion_point(global_scope)
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::std::false_type
    _static_init2_ [[maybe_unused]] =
        (::_pbi::AddDescriptors(&descriptor_table_perip2s_2eproto),
         ::std::false_type{});
#include "google/protobuf/port_undef.inc"
