// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: perip2s.proto
// Protobuf C++ Version: 7.35.1

#ifndef perip2s_2eproto_2epb_2eh
#define perip2s_2eproto_2epb_2eh

#include <limits>
#include <string>
#include <type_traits>
#include <utility>

// clang-format off
#include "google/protobuf/runtime_version.h"
#if PROTOBUF_VERSION != 7035001
#error "Protobuf C++ gencode is built with an incompatible version of"
#error "Protobuf C++ headers/runtime. See"
#error "https://protobuf.dev/support/cross-version-runtime-guarantee/#cpp"
#endif
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/arena.h"
#include "google/protobuf/arenastring.h"
#include "google/protobuf/generated_message_bases.h"
#include "google/protobuf/generated_message_tctable_decl.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/metadata_lite.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/message.h"
#include "google/protobuf/message_lite.h"
#include "google/protobuf/repeated_field.h"  // IWYU pragma: export
#include "google/protobuf/extension_set.h"  // IWYU pragma: export
#include "google/protobuf/generated_enum_reflection.h"
#include "google/protobuf/unknown_field_set.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"

#define PROTOBUF_INTERNAL_EXPORT_perip2s_2eproto

namespace google {
namespace protobuf {
namespace internal {
template <typename T>
::absl::string_view GetAnyMessageName();
}  // namespace internal
}  // namespace protobuf
}  // namespace google

// Internal implementation detail -- do not use these members.
struct TableStruct_perip2s_2eproto {
  static const ::uint32_t offsets[];
};
extern "C" {
extern const ::google::protobuf::internal::DescriptorTable descriptor_table_perip2s_2eproto;
}  // extern "C"
namespace peripheral {
namespace proto {
enum CmdType : int;
extern const uint32_t CmdType_internal_data_[];
class Heartbeat;
struct HeartbeatGlobalsTypeInternal;
#ifndef PROTOBUF_MESSAGE_GLOBALS
extern HeartbeatGlobalsTypeInternal Heartbeat_globals_;
extern const ::google::protobuf::internal::ClassDataFull Heartbeat_class_data_;
#else
extern const HeartbeatGlobalsTypeInternal Heartbeat_globals_;
#endif  // PROTOBUF_MESSAGE_GLOBALS
class P2SBoatPositioningSysRegister;
struct P2SBoatPositioningSysRegisterGlobalsTypeInternal;
#ifndef PROTOBUF_MESSAGE_GLOBALS
extern P2SBoatPositioningSysRegisterGlobalsTypeInternal P2SBoatPositioningSysRegister_globals_;
extern const ::google::protobuf::internal::ClassDataFull P2SBoatPositioningSysRegister_class_data_;
#else
extern const P2SBoatPositioningSysRegisterGlobalsTypeInternal P2SBoatPositioningSysRegister_globals_;
#endif  // PROTOBUF_MESSAGE_GLOBALS
class P2SBoatPositioningSysUpdatePoint;
struct P2SBoatPositioningSysUpdatePointGlobalsTypeInternal;
#ifndef PROTOBUF_MESSAGE_GLOBALS
extern P2SBoatPositioningSysUpdatePointGlobalsTypeInternal P2SBoatPositioningSysUpdatePoint_globals_;
extern const ::google::protobuf::internal::ClassDataFull P2SBoatPositioningSysUpdatePoint_class_data_;
#else
extern const P2SBoatPositioningSysUpdatePointGlobalsTypeInternal P2SBoatPositioningSysUpdatePoint_globals_;
#endif  // PROTOBUF_MESSAGE_GLOBALS
class P2SBoatPositioningSysUpdatePos;
struct P2SBoatPositioningSysUpdatePosGlobalsTypeInternal;
#ifndef PROTOBUF_MESSAGE_GLOBALS
extern P2SBoatPositioningSysUpdatePosGlobalsTypeInternal P2SBoatPositioningSysUpdatePos_globals_;
extern const ::google::protobuf::internal::ClassDataFull P2SBoatPositioningSysUpdatePos_class_data_;
#else
extern const P2SBoatPositioningSysUpdatePosGlobalsTypeInternal P2SBoatPositioningSysUpdatePos_globals_;
#endif  // PROTOBUF_MESSAGE_GLOBALS
class Position;
struct PositionGlobalsTypeInternal;
#ifndef PROTOBUF_MESSAGE_GLOBALS
extern PositionGlobalsTypeInternal Position_globals_;
extern const ::google::protobuf::internal::ClassDataFull Position_class_data_;
#else
extern const PositionGlobalsTypeInternal Position_globals_;
#endif  // PROTOBUF_MESSAGE_GLOBALS
class S2PBoatPositioningSysRegister;
struct S2PBoatPositioningSysRegisterGlobalsTypeInternal;
#ifndef PROTOBUF_MESSAGE_GLOBALS
extern S2PBoatPositioningSysRegisterGlobalsTypeInternal S2PBoatPositioningSysRegister_globals_;
extern const ::google::protobuf::internal::ClassDataFull S2PBoatPositioningSysRegister_class_data_;
#else
extern const S2PBoatPositioningSysRegisterGlobalsTypeInternal S2PBoatPositioningSysRegister_globals_;
#endif  // PROTOBUF_MESSAGE_GLOBALS
}  // namespace proto
}  // namespace peripheral
namespace google {
namespace protobuf {
template <>
internal::EnumTraitsT<::peripheral::proto::CmdType_internal_data_>
    internal::EnumTraitsImpl::value<::peripheral::proto::CmdType>;
}  // namespace protobuf
}  // namespace google

namespace peripheral {
namespace proto {
enum CmdType : int {
  CMD_MIN = 0,
  CMD_HEARTBEAT = 1,
  CMD_PERIP2SERVER_MIN = 1601,
  CMD_P2S_BOAT_POSITIONING_SYS_REGISTER = 1602,
  CMD_P2S_BOAT_POSITIONING_SYS_UPDATE_POS = 1603,
  CMD_P2S_BOAT_POSITIONING_SYS_UPDATE_POINT = 1604,
  CMD_PERIP2SERVER_MAX = 1700,
  CMD_SERVER2PERIP_MIN = 1701,
  CMD_S2P_BOAT_POSITIONING_SYS_REGISTER = 1702,
  CMD_SERVER2PERIP_MAX = 1800,
  CmdType_INT_MIN_SENTINEL_DO_NOT_USE_ =
      ::std::numeric_limits<::int32_t>::min(),
  CmdType_INT_MAX_SENTINEL_DO_NOT_USE_ =
      ::std::numeric_limits<::int32_t>::max(),
};

extern const uint32_t CmdType_internal_data_[];
inline constexpr CmdType CmdType_MIN =
    static_cast<CmdType>(0);
inline constexpr CmdType CmdType_MAX =
    static_cast<CmdType>(1800);
[[nodiscard]] inline bool CmdType_IsValid(int value) {
  return ::google::protobuf::internal::ValidateEnum(value, CmdType_internal_data_);
}
inline constexpr int CmdType_ARRAYSIZE = 1800 + 1;
[[nodiscard]] const ::google::protobuf::EnumDescriptor* PROTOBUF_NONNULL
CmdType_descriptor();
[[nodiscard]] inline auto ProtobufInternalGetEnumDescriptor(CmdType) {
  return CmdType_descriptor();
}
template <typename T>
[[nodiscard]] const ::std::string& CmdType_Name(T value) {
  static_assert(::std::is_same<T, CmdType>::value ||
                    ::std::is_integral<T>::value,
                "Incorrect type passed to CmdType_Name().");
  return ::google::protobuf::internal::NameOfEnum(CmdType_descriptor(), value);
}
[[nodiscard]] inline bool CmdType_Parse(
    ::absl::string_view name, CmdType* PROTOBUF_NONNULL value) {
  return ::google::protobuf::internal::ParseNamedEnum<CmdType>(CmdType_descriptor(), name,
                                           value);
}
using ::google::protobuf::internal::generated_enum::AbslParseFlag;
using ::google::protobuf::internal::generated_enum::AbslUnparseFlag;

// ===================================================================


// -------------------------------------------------------------------

class  PROTOBUF_FUTURE_ADD_EARLY_WARN_UNUSED S2PBoatPositioningSysRegister final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:peripheral.proto.S2PBoatPositioningSysRegister) */ {
 public:
  inline S2PBoatPositioningSysRegister() : S2PBoatPositioningSysRegister(nullptr) {}
  ~S2PBoatPositioningSysRegister() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(S2PBoatPositioningSysRegister* PROTOBUF_NONNULL msg, ::std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(S2PBoatPositioningSysRegister));
  }
#endif

  template <typename = void>
  explicit constexpr S2PBoatPositioningSysRegister(::google::protobuf::internal::ConstantInitialized,
                           const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL
                               class_data);

  inline S2PBoatPositioningSysRegister(const S2PBoatPositioningSysRegister& from) : S2PBoatPositioningSysRegister(nullptr, from) {}
  inline S2PBoatPositioningSysRegister(S2PBoatPositioningSysRegister&& from) noexcept : S2PBoatPositioningSysRegister(nullptr, ::std::move(from)) {}
  inline S2PBoatPositioningSysRegister& operator=(const S2PBoatPositioningSysRegister& from) {
    CopyFrom(from);
    return *this;
  }
  inline S2PBoatPositioningSysRegister& operator=(S2PBoatPositioningSysRegister&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  [[nodiscard]] inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  [[nodiscard]] inline ::google::protobuf::UnknownFieldSet* PROTOBUF_NONNULL
  mutable_unknown_fields() ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  [[nodiscard]] static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL descriptor() {
    return GetDescriptor();
  }
  [[nodiscard]] static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL
  GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  [[nodiscard]] static const ::google::protobuf::Reflection* PROTOBUF_NONNULL GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  [[nodiscard]] static const S2PBoatPositioningSysRegister& default_instance() {
    return *::google::protobuf::internal::MessageGlobalsBase::ToDefaultInstance<S2PBoatPositioningSysRegister>(&S2PBoatPositioningSysRegister_globals_);
  }
  static constexpr int kIndexInFileMessages = 2;
  friend void swap(S2PBoatPositioningSysRegister& a, S2PBoatPositioningSysRegister& b) { a.Swap(&b); }
  inline void Swap(S2PBoatPositioningSysRegister* PROTOBUF_NONNULL other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(S2PBoatPositioningSysRegister* PROTOBUF_NONNULL other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  [[nodiscard]] S2PBoatPositioningSysRegister* PROTOBUF_NONNULL
  New(::google::protobuf::Arena* PROTOBUF_NULLABLE arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<S2PBoatPositioningSysRegister>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const S2PBoatPositioningSysRegister& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const S2PBoatPositioningSysRegister& from) { S2PBoatPositioningSysRegister::MergeImpl(*this, from); }

  private:
  static void MergeImpl(::google::protobuf::MessageLite& to_msg,
                        const ::google::protobuf::MessageLite& from_msg);

  public:
  [[nodiscard]] bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  [[nodiscard]] static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  [[nodiscard]] static ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      const ::google::protobuf::MessageLite& msg, ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream);

  public:
  [[nodiscard]] ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  [[nodiscard]] ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  [[nodiscard]] ::size_t ByteSizeLong() const final;
  [[nodiscard]] ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  [[nodiscard]] int GetCachedSize() const {
    return _impl_._cached_size_.Get();
  }

  private:
  void SharedCtor(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(S2PBoatPositioningSysRegister* PROTOBUF_NONNULL other);
 private:
  template <typename T>
  friend ::absl::string_view(::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "peripheral.proto.S2PBoatPositioningSysRegister"; }

  explicit S2PBoatPositioningSysRegister(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  S2PBoatPositioningSysRegister(::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const S2PBoatPositioningSysRegister& from);
  S2PBoatPositioningSysRegister(
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, S2PBoatPositioningSysRegister&& from) noexcept
      : S2PBoatPositioningSysRegister(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL GetClassData() const PROTOBUF_FINAL;
  static void* PROTOBUF_NONNULL PlacementNew_(
      const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static constexpr auto InternalNewImpl_();

 public:
  static constexpr auto InternalGenerateClassData_(
      const MessageLite& prototype,
      const ::google::protobuf::internal::TcParseTableBase* PROTOBUF_NULLABLE tc_table = nullptr);

  [[nodiscard]] ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kRetFieldNumber = 1,
  };
  // int32 ret = 1;
  void clear_ret() ;
  [[nodiscard]] ::int32_t ret() const;
  void set_ret(::int32_t value);

  private:
  ::int32_t _internal_ret() const;
  void _internal_set_ret(::int32_t value);

  public:
  // @@protoc_insertion_point(class_scope:peripheral.proto.S2PBoatPositioningSysRegister)
 private:
  class _Internal;
  using ParseTableT_ =
      ::google::protobuf::internal::TcParseTable<0, 1,
                          0, 0,
                          2>;
  static constexpr ParseTableT_ InternalGenerateParseTable_(
      const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL class_data);
  friend class ::google::protobuf::internal::TcParser;
  #ifndef PROTOBUF_MESSAGE_GLOBALS
  static const ParseTableT_ _table_;
  #endif

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  friend ::google::protobuf::internal::PrivateAccess;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(::google::protobuf::internal::InternalVisibility visibility,
                                    ::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
        const S2PBoatPositioningSysRegister& from_msg);
    ::google::protobuf::internal::HasBits<1> _has_bits_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    ::int32_t ret_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_perip2s_2eproto;
};
// -------------------------------------------------------------------

class  PROTOBUF_FUTURE_ADD_EARLY_WARN_UNUSED Position final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:peripheral.proto.Position) */ {
 public:
  inline Position() : Position(nullptr) {}
  ~Position() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(Position* PROTOBUF_NONNULL msg, ::std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(Position));
  }
#endif

  template <typename = void>
  explicit constexpr Position(::google::protobuf::internal::ConstantInitialized,
                           const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL
                               class_data);

  inline Position(const Position& from) : Position(nullptr, from) {}
  inline Position(Position&& from) noexcept : Position(nullptr, ::std::move(from)) {}
  inline Position& operator=(const Position& from) {
    CopyFrom(from);
    return *this;
  }
  inline Position& operator=(Position&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  [[nodiscard]] inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  [[nodiscard]] inline ::google::protobuf::UnknownFieldSet* PROTOBUF_NONNULL
  mutable_unknown_fields() ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  [[nodiscard]] static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL descriptor() {
    return GetDescriptor();
  }
  [[nodiscard]] static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL
  GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  [[nodiscard]] static const ::google::protobuf::Reflection* PROTOBUF_NONNULL GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  [[nodiscard]] static const Position& default_instance() {
    return *::google::protobuf::internal::MessageGlobalsBase::ToDefaultInstance<Position>(&Position_globals_);
  }
  static constexpr int kIndexInFileMessages = 3;
  friend void swap(Position& a, Position& b) { a.Swap(&b); }
  inline void Swap(Position* PROTOBUF_NONNULL other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(Position* PROTOBUF_NONNULL other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  [[nodiscard]] Position* PROTOBUF_NONNULL
  New(::google::protobuf::Arena* PROTOBUF_NULLABLE arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<Position>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const Position& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const Position& from) { Position::MergeImpl(*this, from); }

  private:
  static void MergeImpl(::google::protobuf::MessageLite& to_msg,
                        const ::google::protobuf::MessageLite& from_msg);

  public:
  [[nodiscard]] bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  [[nodiscard]] static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  [[nodiscard]] static ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      const ::google::protobuf::MessageLite& msg, ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream);

  public:
  [[nodiscard]] ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  [[nodiscard]] ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  [[nodiscard]] ::size_t ByteSizeLong() const final;
  [[nodiscard]] ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  [[nodiscard]] int GetCachedSize() const {
    return _impl_._cached_size_.Get();
  }

  private:
  void SharedCtor(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(Position* PROTOBUF_NONNULL other);
 private:
  template <typename T>
  friend ::absl::string_view(::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "peripheral.proto.Position"; }

  explicit Position(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  Position(::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Position& from);
  Position(
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, Position&& from) noexcept
      : Position(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL GetClassData() const PROTOBUF_FINAL;
  static void* PROTOBUF_NONNULL PlacementNew_(
      const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static constexpr auto InternalNewImpl_();

 public:
  static constexpr auto InternalGenerateClassData_(
      const MessageLite& prototype,
      const ::google::protobuf::internal::TcParseTableBase* PROTOBUF_NULLABLE tc_table = nullptr);

  [[nodiscard]] ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kXFieldNumber = 1,
    kYFieldNumber = 2,
    kZFieldNumber = 3,
  };
  // float x = 1;
  void clear_x() ;
  [[nodiscard]] float x() const;
  void set_x(float value);

  private:
  float _internal_x() const;
  void _internal_set_x(float value);

  public:
  // float y = 2;
  void clear_y() ;
  [[nodiscard]] float y() const;
  void set_y(float value);

  private:
  float _internal_y() const;
  void _internal_set_y(float value);

  public:
  // float z = 3;
  void clear_z() ;
  [[nodiscard]] float z() const;
  void set_z(float value);

  private:
  float _internal_z() const;
  void _internal_set_z(float value);

  public:
  // @@protoc_insertion_point(class_scope:peripheral.proto.Position)
 private:
  class _Internal;
  using ParseTableT_ =
      ::google::protobuf::internal::TcParseTable<2, 3,
                          0, 0,
                          2>;
  static constexpr ParseTableT_ InternalGenerateParseTable_(
      const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL class_data);
  friend class ::google::protobuf::internal::TcParser;
  #ifndef PROTOBUF_MESSAGE_GLOBALS
  static const ParseTableT_ _table_;
  #endif

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  friend ::google::protobuf::internal::PrivateAccess;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(::google::protobuf::internal::InternalVisibility visibility,
                                    ::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
        const Position& from_msg);
    ::google::protobuf::internal::HasBits<1> _has_bits_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    float x_;
    float y_;
    float z_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_perip2s_2eproto;
};
// -------------------------------------------------------------------

class  PROTOBUF_FUTURE_ADD_EARLY_WARN_UNUSED P2SBoatPositioningSysUpdatePoint final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:peripheral.proto.P2SBoatPositioningSysUpdatePoint) */ {
 public:
  inline P2SBoatPositioningSysUpdatePoint() : P2SBoatPositioningSysUpdatePoint(nullptr) {}
  ~P2SBoatPositioningSysUpdatePoint() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(P2SBoatPositioningSysUpdatePoint* PROTOBUF_NONNULL msg, ::std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(P2SBoatPositioningSysUpdatePoint));
  }
#endif

  template <typename = void>
  explicit constexpr P2SBoatPositioningSysUpdatePoint(::google::protobuf::internal::ConstantInitialized,
                           const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL
                               class_data);

  inline P2SBoatPositioningSysUpdatePoint(const P2SBoatPositioningSysUpdatePoint& from) : P2SBoatPositioningSysUpdatePoint(nullptr, from) {}
  inline P2SBoatPositioningSysUpdatePoint(P2SBoatPositioningSysUpdatePoint&& from) noexcept : P2SBoatPositioningSysUpdatePoint(nullptr, ::std::move(from)) {}
  inline P2SBoatPositioningSysUpdatePoint& operator=(const P2SBoatPositioningSysUpdatePoint& from) {
    CopyFrom(from);
    return *this;
  }
  inline P2SBoatPositioningSysUpdatePoint& operator=(P2SBoatPositioningSysUpdatePoint&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  [[nodiscard]] inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  [[nodiscard]] inline ::google::protobuf::UnknownFieldSet* PROTOBUF_NONNULL
  mutable_unknown_fields() ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  [[nodiscard]] static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL descriptor() {
    return GetDescriptor();
  }
  [[nodiscard]] static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL
  GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  [[nodiscard]] static const ::google::protobuf::Reflection* PROTOBUF_NONNULL GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  [[nodiscard]] static const P2SBoatPositioningSysUpdatePoint& default_instance() {
    return *::google::protobuf::internal::MessageGlobalsBase::ToDefaultInstance<P2SBoatPositioningSysUpdatePoint>(&P2SBoatPositioningSysUpdatePoint_globals_);
  }
  static constexpr int kIndexInFileMessages = 5;
  friend void swap(P2SBoatPositioningSysUpdatePoint& a, P2SBoatPositioningSysUpdatePoint& b) { a.Swap(&b); }
  inline void Swap(P2SBoatPositioningSysUpdatePoint* PROTOBUF_NONNULL other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(P2SBoatPositioningSysUpdatePoint* PROTOBUF_NONNULL other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  [[nodiscard]] P2SBoatPositioningSysUpdatePoint* PROTOBUF_NONNULL
  New(::google::protobuf::Arena* PROTOBUF_NULLABLE arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<P2SBoatPositioningSysUpdatePoint>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const P2SBoatPositioningSysUpdatePoint& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const P2SBoatPositioningSysUpdatePoint& from) { P2SBoatPositioningSysUpdatePoint::MergeImpl(*this, from); }

  private:
  static void MergeImpl(::google::protobuf::MessageLite& to_msg,
                        const ::google::protobuf::MessageLite& from_msg);

  public:
  [[nodiscard]] bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  [[nodiscard]] static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  [[nodiscard]] static ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      const ::google::protobuf::MessageLite& msg, ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream);

  public:
  [[nodiscard]] ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  [[nodiscard]] ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  [[nodiscard]] ::size_t ByteSizeLong() const final;
  [[nodiscard]] ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  [[nodiscard]] int GetCachedSize() const {
    return _impl_._cached_size_.Get();
  }

  private:
  void SharedCtor(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(P2SBoatPositioningSysUpdatePoint* PROTOBUF_NONNULL other);
 private:
  template <typename T>
  friend ::absl::string_view(::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "peripheral.proto.P2SBoatPositioningSysUpdatePoint"; }

  explicit P2SBoatPositioningSysUpdatePoint(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  P2SBoatPositioningSysUpdatePoint(::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const P2SBoatPositioningSysUpdatePoint& from);
  P2SBoatPositioningSysUpdatePoint(
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, P2SBoatPositioningSysUpdatePoint&& from) noexcept
      : P2SBoatPositioningSysUpdatePoint(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL GetClassData() const PROTOBUF_FINAL;
  static void* PROTOBUF_NONNULL PlacementNew_(
      const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static constexpr auto InternalNewImpl_();

 public:
  static constexpr auto InternalGenerateClassData_(
      const MessageLite& prototype,
      const ::google::protobuf::internal::TcParseTableBase* PROTOBUF_NULLABLE tc_table = nullptr);

  [[nodiscard]] ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kBoatIdFieldNumber = 1,
    kPointIdFieldNumber = 2,
    kTimestampFieldNumber = 3,
  };
  // int32 boat_id = 1;
  void clear_boat_id() ;
  [[nodiscard]] ::int32_t boat_id() const;
  void set_boat_id(::int32_t value);

  private:
  ::int32_t _internal_boat_id() const;
  void _internal_set_boat_id(::int32_t value);

  public:
  // int32 point_id = 2;
  void clear_point_id() ;
  [[nodiscard]] ::int32_t point_id() const;
  void set_point_id(::int32_t value);

  private:
  ::int32_t _internal_point_id() const;
  void _internal_set_point_id(::int32_t value);

  public:
  // int64 timestamp = 3;
  void clear_timestamp() ;
  [[nodiscard]] ::int64_t timestamp() const;
  void set_timestamp(::int64_t value);

  private:
  ::int64_t _internal_timestamp() const;
  void _internal_set_timestamp(::int64_t value);

  public:
  // @@protoc_insertion_point(class_scope:peripheral.proto.P2SBoatPositioningSysUpdatePoint)
 private:
  class _Internal;
  using ParseTableT_ =
      ::google::protobuf::internal::TcParseTable<2, 3,
                          0, 0,
                          2>;
  static constexpr ParseTableT_ InternalGenerateParseTable_(
      const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL class_data);
  friend class ::google::protobuf::internal::TcParser;
  #ifndef PROTOBUF_MESSAGE_GLOBALS
  static const ParseTableT_ _table_;
  #endif

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  friend ::google::protobuf::internal::PrivateAccess;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(::google::protobuf::internal::InternalVisibility visibility,
                                    ::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
        const P2SBoatPositioningSysUpdatePoint& from_msg);
    ::google::protobuf::internal::HasBits<1> _has_bits_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    ::int32_t boat_id_;
    ::int32_t point_id_;
    ::int64_t timestamp_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_perip2s_2eproto;
};
// -------------------------------------------------------------------

class  PROTOBUF_FUTURE_ADD_EARLY_WARN_UNUSED P2SBoatPositioningSysRegister final : public ::google::protobuf::internal::ZeroFieldsBase
/* @@protoc_insertion_point(class_definition:peripheral.proto.P2SBoatPositioningSysRegister) */ {
 public:
  inline P2SBoatPositioningSysRegister() : P2SBoatPositioningSysRegister(nullptr) {}

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(P2SBoatPositioningSysRegister* PROTOBUF_NONNULL msg, ::std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(P2SBoatPositioningSysRegister));
  }
#endif

  template <typename = void>
  explicit constexpr P2SBoatPositioningSysRegister(::google::protobuf::internal::ConstantInitialized,
                           const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL
                               class_data);

  inline P2SBoatPositioningSysRegister(const P2SBoatPositioningSysRegister& from) : P2SBoatPositioningSysRegister(nullptr, from) {}
  inline P2SBoatPositioningSysRegister(P2SBoatPositioningSysRegister&& from) noexcept : P2SBoatPositioningSysRegister(nullptr, ::std::move(from)) {}
  inline P2SBoatPositioningSysRegister& operator=(const P2SBoatPositioningSysRegister& from) {
    CopyFrom(from);
    return *this;
  }
  inline P2SBoatPositioningSysRegister& operator=(P2SBoatPositioningSysRegister&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  [[nodiscard]] inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  [[nodiscard]] inline ::google::protobuf::UnknownFieldSet* PROTOBUF_NONNULL
  mutable_unknown_fields() ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  [[nodiscard]] static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL descriptor() {
    return GetDescriptor();
  }
  [[nodiscard]] static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL
  GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  [[nodiscard]] static const ::google::protobuf::Reflection* PROTOBUF_NONNULL GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  [[nodiscard]] static const P2SBoatPositioningSysRegister& default_instance() {
    return *::google::protobuf::internal::MessageGlobalsBase::ToDefaultInstance<P2SBoatPositioningSysRegister>(&P2SBoatPositioningSysRegister_globals_);
  }
  static constexpr int kIndexInFileMessages = 1;
  friend void swap(P2SBoatPositioningSysRegister& a, P2SBoatPositioningSysRegister& b) { a.Swap(&b); }
  inline void Swap(P2SBoatPositioningSysRegister* PROTOBUF_NONNULL other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(P2SBoatPositioningSysRegister* PROTOBUF_NONNULL other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  [[nodiscard]] P2SBoatPositioningSysRegister* PROTOBUF_NONNULL
  New(::google::protobuf::Arena* PROTOBUF_NULLABLE arena = nullptr) const {
    return ::google::protobuf::internal::ZeroFieldsBase::DefaultConstruct<P2SBoatPositioningSysRegister>(arena);
  }
  using ::google::protobuf::internal::ZeroFieldsBase::CopyFrom;
  inline void CopyFrom(const P2SBoatPositioningSysRegister& from) { ::google::protobuf::internal::ZeroFieldsBase::CopyImpl(*this, from); }
  using ::google::protobuf::internal::ZeroFieldsBase::MergeFrom;
  void MergeFrom(const P2SBoatPositioningSysRegister& from) { ::google::protobuf::internal::ZeroFieldsBase::MergeImpl(*this, from); }

  public:
  [[nodiscard]] bool IsInitialized() const {
    return true;
  }
 private:
  template <typename T>
  friend ::absl::string_view(::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "peripheral.proto.P2SBoatPositioningSysRegister"; }

  explicit P2SBoatPositioningSysRegister(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  P2SBoatPositioningSysRegister(::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const P2SBoatPositioningSysRegister& from);
  P2SBoatPositioningSysRegister(
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, P2SBoatPositioningSysRegister&& from) noexcept
      : P2SBoatPositioningSysRegister(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL GetClassData() const PROTOBUF_FINAL;
  static void* PROTOBUF_NONNULL PlacementNew_(
      const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static constexpr auto InternalNewImpl_();

 public:
  static constexpr auto InternalGenerateClassData_(
      const MessageLite& prototype,
      const ::google::protobuf::internal::TcParseTableBase* PROTOBUF_NULLABLE tc_table = nullptr);

  [[nodiscard]] ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  // @@protoc_insertion_point(class_scope:peripheral.proto.P2SBoatPositioningSysRegister)
 private:
  class _Internal;
  using ParseTableT_ =
      ::google::protobuf::internal::TcParseTable<0, 0,
                          0, 0,
                          2>;
  static constexpr ParseTableT_ InternalGenerateParseTable_(
      const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL class_data);
  friend class ::google::protobuf::internal::TcParser;
  #ifndef PROTOBUF_MESSAGE_GLOBALS
  static const ParseTableT_ _table_;
  #endif

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  friend ::google::protobuf::internal::PrivateAccess;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  friend struct ::TableStruct_perip2s_2eproto;
};
// -------------------------------------------------------------------

class  PROTOBUF_FUTURE_ADD_EARLY_WARN_UNUSED Heartbeat final : public ::google::protobuf::internal::ZeroFieldsBase
/* @@protoc_insertion_point(class_definition:peripheral.proto.Heartbeat) */ {
 public:
  inline Heartbeat() : Heartbeat(nullptr) {}

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(Heartbeat* PROTOBUF_NONNULL msg, ::std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(Heartbeat));
  }
#endif

  template <typename = void>
  explicit constexpr Heartbeat(::google::protobuf::internal::ConstantInitialized,
                           const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL
                               class_data);

  inline Heartbeat(const Heartbeat& from) : Heartbeat(nullptr, from) {}
  inline Heartbeat(Heartbeat&& from) noexcept : Heartbeat(nullptr, ::std::move(from)) {}
  inline Heartbeat& operator=(const Heartbeat& from) {
    CopyFrom(from);
    return *this;
  }
  inline Heartbeat& operator=(Heartbeat&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  [[nodiscard]] inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  [[nodiscard]] inline ::google::protobuf::UnknownFieldSet* PROTOBUF_NONNULL
  mutable_unknown_fields() ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  [[nodiscard]] static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL descriptor() {
    return GetDescriptor();
  }
  [[nodiscard]] static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL
  GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  [[nodiscard]] static const ::google::protobuf::Reflection* PROTOBUF_NONNULL GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  [[nodiscard]] static const Heartbeat& default_instance() {
    return *::google::protobuf::internal::MessageGlobalsBase::ToDefaultInstance<Heartbeat>(&Heartbeat_globals_);
  }
  static constexpr int kIndexInFileMessages = 0;
  friend void swap(Heartbeat& a, Heartbeat& b) { a.Swap(&b); }
  inline void Swap(Heartbeat* PROTOBUF_NONNULL other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(Heartbeat* PROTOBUF_NONNULL other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  [[nodiscard]] Heartbeat* PROTOBUF_NONNULL
  New(::google::protobuf::Arena* PROTOBUF_NULLABLE arena = nullptr) const {
    return ::google::protobuf::internal::ZeroFieldsBase::DefaultConstruct<Heartbeat>(arena);
  }
  using ::google::protobuf::internal::ZeroFieldsBase::CopyFrom;
  inline void CopyFrom(const Heartbeat& from) { ::google::protobuf::internal::ZeroFieldsBase::CopyImpl(*this, from); }
  using ::google::protobuf::internal::ZeroFieldsBase::MergeFrom;
  void MergeFrom(const Heartbeat& from) { ::google::protobuf::internal::ZeroFieldsBase::MergeImpl(*this, from); }

  public:
  [[nodiscard]] bool IsInitialized() const {
    return true;
  }
 private:
  template <typename T>
  friend ::absl::string_view(::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "peripheral.proto.Heartbeat"; }

  explicit Heartbeat(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  Heartbeat(::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Heartbeat& from);
  Heartbeat(
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, Heartbeat&& from) noexcept
      : Heartbeat(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL GetClassData() const PROTOBUF_FINAL;
  static void* PROTOBUF_NONNULL PlacementNew_(
      const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static constexpr auto InternalNewImpl_();

 public:
  static constexpr auto InternalGenerateClassData_(
      const MessageLite& prototype,
      const ::google::protobuf::internal::TcParseTableBase* PROTOBUF_NULLABLE tc_table = nullptr);

  [[nodiscard]] ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  // @@protoc_insertion_point(class_scope:peripheral.proto.Heartbeat)
 private:
  class _Internal;
  using ParseTableT_ =
      ::google::protobuf::internal::TcParseTable<0, 0,
                          0, 0,
                          2>;
  static constexpr ParseTableT_ InternalGenerateParseTable_(
      const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL class_data);
  friend class ::google::protobuf::internal::TcParser;
  #ifndef PROTOBUF_MESSAGE_GLOBALS
  static const ParseTableT_ _table_;
  #endif

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  friend ::google::protobuf::internal::PrivateAccess;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  friend struct ::TableStruct_perip2s_2eproto;
};
// -------------------------------------------------------------------

class  PROTOBUF_FUTURE_ADD_EARLY_WARN_UNUSED P2SBoatPositioningSysUpdatePos final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:peripheral.proto.P2SBoatPositioningSysUpdatePos) */ {
 public:
  inline P2SBoatPositioningSysUpdatePos() : P2SBoatPositioningSysUpdatePos(nullptr) {}
  ~P2SBoatPositioningSysUpdatePos() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(P2SBoatPositioningSysUpdatePos* PROTOBUF_NONNULL msg, ::std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(P2SBoatPositioningSysUpdatePos));
  }
#endif

  template <typename = void>
  explicit constexpr P2SBoatPositioningSysUpdatePos(::google::protobuf::internal::ConstantInitialized,
                           const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL
                               class_data);

  inline P2SBoatPositioningSysUpdatePos(const P2SBoatPositioningSysUpdatePos& from) : P2SBoatPositioningSysUpdatePos(nullptr, from) {}
  inline P2SBoatPositioningSysUpdatePos(P2SBoatPositioningSysUpdatePos&& from) noexcept : P2SBoatPositioningSysUpdatePos(nullptr, ::std::move(from)) {}
  inline P2SBoatPositioningSysUpdatePos& operator=(const P2SBoatPositioningSysUpdatePos& from) {
    CopyFrom(from);
    return *this;
  }
  inline P2SBoatPositioningSysUpdatePos& operator=(P2SBoatPositioningSysUpdatePos&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  [[nodiscard]] inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  [[nodiscard]] inline ::google::protobuf::UnknownFieldSet* PROTOBUF_NONNULL
  mutable_unknown_fields() ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  [[nodiscard]] static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL descriptor() {
    return GetDescriptor();
  }
  [[nodiscard]] static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL
  GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  [[nodiscard]] static const ::google::protobuf::Reflection* PROTOBUF_NONNULL GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  [[nodiscard]] static const P2SBoatPositioningSysUpdatePos& default_instance() {
    return *::google::protobuf::internal::MessageGlobalsBase::ToDefaultInstance<P2SBoatPositioningSysUpdatePos>(&P2SBoatPositioningSysUpdatePos_globals_);
  }
  static constexpr int kIndexInFileMessages = 4;
  friend void swap(P2SBoatPositioningSysUpdatePos& a, P2SBoatPositioningSysUpdatePos& b) { a.Swap(&b); }
  inline void Swap(P2SBoatPositioningSysUpdatePos* PROTOBUF_NONNULL other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(P2SBoatPositioningSysUpdatePos* PROTOBUF_NONNULL other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  [[nodiscard]] P2SBoatPositioningSysUpdatePos* PROTOBUF_NONNULL
  New(::google::protobuf::Arena* PROTOBUF_NULLABLE arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<P2SBoatPositioningSysUpdatePos>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const P2SBoatPositioningSysUpdatePos& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const P2SBoatPositioningSysUpdatePos& from) { P2SBoatPositioningSysUpdatePos::MergeImpl(*this, from); }

  private:
  static void MergeImpl(::google::protobuf::MessageLite& to_msg,
                        const ::google::protobuf::MessageLite& from_msg);

  public:
  [[nodiscard]] bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  [[nodiscard]] static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  [[nodiscard]] static ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      const ::google::protobuf::MessageLite& msg, ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream);

  public:
  [[nodiscard]] ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  [[nodiscard]] ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  [[nodiscard]] ::size_t ByteSizeLong() const final;
  [[nodiscard]] ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  [[nodiscard]] int GetCachedSize() const {
    return _impl_._cached_size_.Get();
  }

  private:
  void SharedCtor(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(P2SBoatPositioningSysUpdatePos* PROTOBUF_NONNULL other);
 private:
  template <typename T>
  friend ::absl::string_view(::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "peripheral.proto.P2SBoatPositioningSysUpdatePos"; }

  explicit P2SBoatPositioningSysUpdatePos(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  P2SBoatPositioningSysUpdatePos(::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const P2SBoatPositioningSysUpdatePos& from);
  P2SBoatPositioningSysUpdatePos(
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, P2SBoatPositioningSysUpdatePos&& from) noexcept
      : P2SBoatPositioningSysUpdatePos(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL GetClassData() const PROTOBUF_FINAL;
  static void* PROTOBUF_NONNULL PlacementNew_(
      const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static constexpr auto InternalNewImpl_();

 public:
  static constexpr auto InternalGenerateClassData_(
      const MessageLite& prototype,
      const ::google::protobuf::internal::TcParseTableBase* PROTOBUF_NULLABLE tc_table = nullptr);

  [[nodiscard]] ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kPosFieldNumber = 2,
    kTimestampFieldNumber = 3,
    kBoatIdFieldNumber = 1,
  };
  // .peripheral.proto.Position pos = 2;
  [[nodiscard]] bool has_pos()
      const;
  void clear_pos() ;
  [[nodiscard]] const ::peripheral::proto::Position& pos() const;
  [[nodiscard]] ::peripheral::proto::Position* PROTOBUF_NULLABLE release_pos();
  ::peripheral::proto::Position* PROTOBUF_NONNULL mutable_pos();
  void set_allocated_pos(::peripheral::proto::Position* PROTOBUF_NULLABLE value);
  void unsafe_arena_set_allocated_pos(::peripheral::proto::Position* PROTOBUF_NULLABLE value);
  ::peripheral::proto::Position* PROTOBUF_NULLABLE unsafe_arena_release_pos();

  private:
  const ::peripheral::proto::Position& _internal_pos() const;
  ::peripheral::proto::Position* PROTOBUF_NONNULL _internal_mutable_pos();

  public:
  // int64 timestamp = 3;
  void clear_timestamp() ;
  [[nodiscard]] ::int64_t timestamp() const;
  void set_timestamp(::int64_t value);

  private:
  ::int64_t _internal_timestamp() const;
  void _internal_set_timestamp(::int64_t value);

  public:
  // int32 boat_id = 1;
  void clear_boat_id() ;
  [[nodiscard]] ::int32_t boat_id() const;
  void set_boat_id(::int32_t value);

  private:
  ::int32_t _internal_boat_id() const;
  void _internal_set_boat_id(::int32_t value);

  public:
  // @@protoc_insertion_point(class_scope:peripheral.proto.P2SBoatPositioningSysUpdatePos)
 private:
  class _Internal;
  using ParseTableT_ =
      ::google::protobuf::internal::TcParseTable<2, 3,
                          1, 0,
                          2>;
  static constexpr ParseTableT_ InternalGenerateParseTable_(
      const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL class_data);
  friend class ::google::protobuf::internal::TcParser;
  #ifndef PROTOBUF_MESSAGE_GLOBALS
  static const ParseTableT_ _table_;
  #endif

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  friend ::google::protobuf::internal::PrivateAccess;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(::google::protobuf::internal::InternalVisibility visibility,
                                    ::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
        const P2SBoatPositioningSysUpdatePos& from_msg);
    ::google::protobuf::internal::HasBits<1> _has_bits_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    ::peripheral::proto::Position* PROTOBUF_NULLABLE pos_;
    ::int64_t timestamp_;
    ::int32_t boat_id_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_perip2s_2eproto;
};

// ===================================================================




// ===================================================================


#ifdef __GNUC__
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// -------------------------------------------------------------------

// Heartbeat

// -------------------------------------------------------------------

// P2SBoatPositioningSysRegister

// -------------------------------------------------------------------

// S2PBoatPositioningSysRegister

// int32 ret = 1;
inline void S2PBoatPositioningSysRegister::clear_ret() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.ret_ = 0;
  ClearHasBit(_impl_._has_bits_[0], 0x00000001U);
}
inline ::int32_t S2PBoatPositioningSysRegister::ret() const {
  // @@protoc_insertion_point(field_get:peripheral.proto.S2PBoatPositioningSysRegister.ret)
  return _internal_ret();
}
inline void S2PBoatPositioningSysRegister::set_ret(::int32_t value) {
  _internal_set_ret(value);
  SetHasBit(_impl_._has_bits_[0], 0x00000001U);
  // @@protoc_insertion_point(field_set:peripheral.proto.S2PBoatPositioningSysRegister.ret)
}
inline ::int32_t S2PBoatPositioningSysRegister::_internal_ret() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.ret_;
}
inline void S2PBoatPositioningSysRegister::_internal_set_ret(::int32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.ret_ = value;
}

// -------------------------------------------------------------------

// Position

// float x = 1;
inline void Position::clear_x() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.x_ = 0;
  ClearHasBit(_impl_._has_bits_[0], 0x00000001U);
}
inline float Position::x() const {
  // @@protoc_insertion_point(field_get:peripheral.proto.Position.x)
  return _internal_x();
}
inline void Position::set_x(float value) {
  _internal_set_x(value);
  SetHasBit(_impl_._has_bits_[0], 0x00000001U);
  // @@protoc_insertion_point(field_set:peripheral.proto.Position.x)
}
inline float Position::_internal_x() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.x_;
}
inline void Position::_internal_set_x(float value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.x_ = value;
}

// float y = 2;
inline void Position::clear_y() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.y_ = 0;
  ClearHasBit(_impl_._has_bits_[0], 0x00000002U);
}
inline float Position::y() const {
  // @@protoc_insertion_point(field_get:peripheral.proto.Position.y)
  return _internal_y();
}
inline void Position::set_y(float value) {
  _internal_set_y(value);
  SetHasBit(_impl_._has_bits_[0], 0x00000002U);
  // @@protoc_insertion_point(field_set:peripheral.proto.Position.y)
}
inline float Position::_internal_y() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.y_;
}
inline void Position::_internal_set_y(float value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.y_ = value;
}

// float z = 3;
inline void Position::clear_z() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.z_ = 0;
  ClearHasBit(_impl_._has_bits_[0], 0x00000004U);
}
inline float Position::z() const {
  // @@protoc_insertion_point(field_get:peripheral.proto.Position.z)
  return _internal_z();
}
inline void Position::set_z(float value) {
  _internal_set_z(value);
  SetHasBit(_impl_._has_bits_[0], 0x00000004U);
  // @@protoc_insertion_point(field_set:peripheral.proto.Position.z)
}
inline float Position::_internal_z() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.z_;
}
inline void Position::_internal_set_z(float value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.z_ = value;
}

// -------------------------------------------------------------------

// P2SBoatPositioningSysUpdatePos

// int32 boat_id = 1;
inline void P2SBoatPositioningSysUpdatePos::clear_boat_id() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.boat_id_ = 0;
  ClearHasBit(_impl_._has_bits_[0], 0x00000004U);
}
inline ::int32_t P2SBoatPositioningSysUpdatePos::boat_id() const {
  // @@protoc_insertion_point(field_get:peripheral.proto.P2SBoatPositioningSysUpdatePos.boat_id)
  return _internal_boat_id();
}
inline void P2SBoatPositioningSysUpdatePos::set_boat_id(::int32_t value) {
  _internal_set_boat_id(value);
  SetHasBit(_impl_._has_bits_[0], 0x00000004U);
  // @@protoc_insertion_point(field_set:peripheral.proto.P2SBoatPositioningSysUpdatePos.boat_id)
}
inline ::int32_t P2SBoatPositioningSysUpdatePos::_internal_boat_id() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.boat_id_;
}
inline void P2SBoatPositioningSysUpdatePos::_internal_set_boat_id(::int32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.boat_id_ = value;
}

// .peripheral.proto.Position pos = 2;
inline bool P2SBoatPositioningSysUpdatePos::has_pos() const {
  bool value = CheckHasBit(_impl_._has_bits_[0], 0x00000001U);
  PROTOBUF_ASSUME(!value || _impl_.pos_ != nullptr);
  return value;
}
inline void P2SBoatPositioningSysUpdatePos::clear_pos() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (_impl_.pos_ != nullptr) _impl_.pos_->Clear();
  ClearHasBit(_impl_._has_bits_[0], 0x00000001U);
}
inline const ::peripheral::proto::Position& P2SBoatPositioningSysUpdatePos::_internal_pos() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  const ::peripheral::proto::Position* p = _impl_.pos_;
  return p != nullptr ? *p : *::google::protobuf::internal::MessageGlobalsBase::ToDefaultInstance<::peripheral::proto::Position>(&::peripheral::proto::Position_globals_);
}
inline const ::peripheral::proto::Position& P2SBoatPositioningSysUpdatePos::pos() const ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:peripheral.proto.P2SBoatPositioningSysUpdatePos.pos)
  return _internal_pos();
}
inline void P2SBoatPositioningSysUpdatePos::unsafe_arena_set_allocated_pos(
    ::peripheral::proto::Position* PROTOBUF_NULLABLE value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (GetArena() == nullptr) {
    delete reinterpret_cast<::google::protobuf::MessageLite*>(_impl_.pos_);
  }
  _impl_.pos_ = reinterpret_cast<::peripheral::proto::Position*>(value);
  if (value != nullptr) {
    SetHasBit(_impl_._has_bits_[0], 0x00000001U);
  } else {
    ClearHasBit(_impl_._has_bits_[0], 0x00000001U);
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:peripheral.proto.P2SBoatPositioningSysUpdatePos.pos)
}
inline ::peripheral::proto::Position* PROTOBUF_NULLABLE P2SBoatPositioningSysUpdatePos::release_pos() {
  ::google::protobuf::internal::TSanWrite(&_impl_);

  ClearHasBit(_impl_._has_bits_[0], 0x00000001U);
  ::peripheral::proto::Position* released = _impl_.pos_;
  _impl_.pos_ = nullptr;
  if (::google::protobuf::internal::DebugHardenForceCopyInRelease()) {
    auto* old = reinterpret_cast<::google::protobuf::MessageLite*>(released);
    released = ::google::protobuf::internal::DuplicateIfNonNull(released);
    if (GetArena() == nullptr) {
      delete old;
    }
  } else {
    if (GetArena() != nullptr) {
      released = ::google::protobuf::internal::DuplicateIfNonNull(released);
    }
  }
  return released;
}
inline ::peripheral::proto::Position* PROTOBUF_NULLABLE P2SBoatPositioningSysUpdatePos::unsafe_arena_release_pos() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:peripheral.proto.P2SBoatPositioningSysUpdatePos.pos)

  ClearHasBit(_impl_._has_bits_[0], 0x00000001U);
  ::peripheral::proto::Position* temp = _impl_.pos_;
  _impl_.pos_ = nullptr;
  return temp;
}
inline ::peripheral::proto::Position* PROTOBUF_NONNULL P2SBoatPositioningSysUpdatePos::_internal_mutable_pos() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (_impl_.pos_ == nullptr) {
    auto* p = ::google::protobuf::Message::DefaultConstruct<::peripheral::proto::Position>(GetArena());
    _impl_.pos_ = reinterpret_cast<::peripheral::proto::Position*>(p);
  }
  return _impl_.pos_;
}
inline ::peripheral::proto::Position* PROTOBUF_NONNULL P2SBoatPositioningSysUpdatePos::mutable_pos()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  SetHasBit(_impl_._has_bits_[0], 0x00000001U);
  ::peripheral::proto::Position* _msg = _internal_mutable_pos();
  // @@protoc_insertion_point(field_mutable:peripheral.proto.P2SBoatPositioningSysUpdatePos.pos)
  return _msg;
}
inline void P2SBoatPositioningSysUpdatePos::set_allocated_pos(::peripheral::proto::Position* PROTOBUF_NULLABLE value) {
  ::google::protobuf::Arena* message_arena = GetArena();
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (message_arena == nullptr) {
    delete reinterpret_cast<::google::protobuf::MessageLite*>(_impl_.pos_);
  }

  if (value != nullptr) {
    ::google::protobuf::Arena* submessage_arena = value->GetArena();
    if (message_arena != submessage_arena) {
      value = ::google::protobuf::internal::GetOwnedMessage(message_arena, value, submessage_arena);
    }
    SetHasBit(_impl_._has_bits_[0], 0x00000001U);
  } else {
    ClearHasBit(_impl_._has_bits_[0], 0x00000001U);
  }

  _impl_.pos_ = reinterpret_cast<::peripheral::proto::Position*>(value);
  // @@protoc_insertion_point(field_set_allocated:peripheral.proto.P2SBoatPositioningSysUpdatePos.pos)
}

// int64 timestamp = 3;
inline void P2SBoatPositioningSysUpdatePos::clear_timestamp() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.timestamp_ = ::int64_t{0};
  ClearHasBit(_impl_._has_bits_[0], 0x00000002U);
}
inline ::int64_t P2SBoatPositioningSysUpdatePos::timestamp() const {
  // @@protoc_insertion_point(field_get:peripheral.proto.P2SBoatPositioningSysUpdatePos.timestamp)
  return _internal_timestamp();
}
inline void P2SBoatPositioningSysUpdatePos::set_timestamp(::int64_t value) {
  _internal_set_timestamp(value);
  SetHasBit(_impl_._has_bits_[0], 0x00000002U);
  // @@protoc_insertion_point(field_set:peripheral.proto.P2SBoatPositioningSysUpdatePos.timestamp)
}
inline ::int64_t P2SBoatPositioningSysUpdatePos::_internal_timestamp() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.timestamp_;
}
inline void P2SBoatPositioningSysUpdatePos::_internal_set_timestamp(::int64_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.timestamp_ = value;
}

// -------------------------------------------------------------------

// P2SBoatPositioningSysUpdatePoint

// int32 boat_id = 1;
inline void P2SBoatPositioningSysUpdatePoint::clear_boat_id() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.boat_id_ = 0;
  ClearHasBit(_impl_._has_bits_[0], 0x00000001U);
}
inline ::int32_t P2SBoatPositioningSysUpdatePoint::boat_id() const {
  // @@protoc_insertion_point(field_get:peripheral.proto.P2SBoatPositioningSysUpdatePoint.boat_id)
  return _internal_boat_id();
}
inline void P2SBoatPositioningSysUpdatePoint::set_boat_id(::int32_t value) {
  _internal_set_boat_id(value);
  SetHasBit(_impl_._has_bits_[0], 0x00000001U);
  // @@protoc_insertion_point(field_set:peripheral.proto.P2SBoatPositioningSysUpdatePoint.boat_id)
}
inline ::int32_t P2SBoatPositioningSysUpdatePoint::_internal_boat_id() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.boat_id_;
}
inline void P2SBoatPositioningSysUpdatePoint::_internal_set_boat_id(::int32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.boat_id_ = value;
}

// int32 point_id = 2;
inline void P2SBoatPositioningSysUpdatePoint::clear_point_id() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.point_id_ = 0;
  ClearHasBit(_impl_._has_bits_[0], 0x00000002U);
}
inline ::int32_t P2SBoatPositioningSysUpdatePoint::point_id() const {
  // @@protoc_insertion_point(field_get:peripheral.proto.P2SBoatPositioningSysUpdatePoint.point_id)
  return _internal_point_id();
}
inline void P2SBoatPositioningSysUpdatePoint::set_point_id(::int32_t value) {
  _internal_set_point_id(value);
  SetHasBit(_impl_._has_bits_[0], 0x00000002U);
  // @@protoc_insertion_point(field_set:peripheral.proto.P2SBoatPositioningSysUpdatePoint.point_id)
}
inline ::int32_t P2SBoatPositioningSysUpdatePoint::_internal_point_id() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.point_id_;
}
inline void P2SBoatPositioningSysUpdatePoint::_internal_set_point_id(::int32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.point_id_ = value;
}

// int64 timestamp = 3;
inline void P2SBoatPositioningSysUpdatePoint::clear_timestamp() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.timestamp_ = ::int64_t{0};
  ClearHasBit(_impl_._has_bits_[0], 0x00000004U);
}
inline ::int64_t P2SBoatPositioningSysUpdatePoint::timestamp() const {
  // @@protoc_insertion_point(field_get:peripheral.proto.P2SBoatPositioningSysUpdatePoint.timestamp)
  return _internal_timestamp();
}
inline void P2SBoatPositioningSysUpdatePoint::set_timestamp(::int64_t value) {
  _internal_set_timestamp(value);
  SetHasBit(_impl_._has_bits_[0], 0x00000004U);
  // @@protoc_insertion_point(field_set:peripheral.proto.P2SBoatPositioningSysUpdatePoint.timestamp)
}
inline ::int64_t P2SBoatPositioningSysUpdatePoint::_internal_timestamp() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.timestamp_;
}
inline void P2SBoatPositioningSysUpdatePoint::_internal_set_timestamp(::int64_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.timestamp_ = value;
}

#ifdef __GNUC__
#pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)
}  // namespace proto
}  // namespace peripheral


namespace google {
namespace protobuf {

template <>
struct is_proto_enum<::peripheral::proto::CmdType> : std::true_type {};
template <>
inline const EnumDescriptor* PROTOBUF_NONNULL GetEnumDescriptor<::peripheral::proto::CmdType>() {
  return ::peripheral::proto::CmdType_descriptor();
}

}  // namespace protobuf
}  // namespace google

// @@protoc_insertion_point(global_scope)

#include "google/protobuf/port_undef.inc"
// clang-format on

#endif  // perip2s_2eproto_2epb_2eh
